# jokes.py

BANANA_JOKES = [
    "Ek kela dusre kele se: Tu itna udas kyun hai?\nDusra kela: Kya karun bhai, main a-kela (akela) hoon na! 🍌😂",
    "Teacher: Kela khane ke kya fayde hain?\nChimpu: Sir, kela khane ke baad chhilke par dushman ko giraya ja sakta hai! 🍌🐒",
    "Customer: 10 rupaye mein ek kela? 5 mein de do!\nDukandar: 5 mein toh sirf chhilka milega.\nCustomer: Ye lo 5 rupaye, chhilka rakh lo aur kela mujhe de do! 🍌😎",
    "Doctor: Roz ek kela khaya karo.\nChimpu: Doctor sahab, main kela khata nahi, kela mera dharam hai! 🍌🐵",
    "Ek Bandar ne sadhu se pucha: Jeevan ka sabse bada sach kya hai?\nSadhu: Beta, kela chahe kitna bhi meetha ho, chhilka utarna hi padta hai! 🍌🤣",
    "Chimpu ki GF: Mere pyaar ki tulna kele se mat karna!\nChimpu: Pata hai jaan, kela ek din kaala pad jata hai par mera pyaar hamesha fresh rahega! 🍌😏",
    "Dost: Bhai tu itna patla kyun ho gaya?\nChimpu: Gym mein trainer ne bola tha 'kela' kha, maine suna 'akela' kha... tab se akele hi kha raha hoon! 🍌😅",
    "Interviewer: Aapki sabse badi kamzori kya hai?\nChimpu: Main kitna bhi gussa hoon, kela dekhte hi pighal jata hoon! 🍌🐒",
    "Teacher: 'Banana' ka plural kya hoga?\nChimpu: Banana shake, sir! 🍌🥤",
    "Police: Tumne chori kyun ki?\nChimpu: Sir, kanoon andha hota hai, par bandar thodi! Samne kela rakha tha, mujhse raha nahi gaya! 🍌🚨",
    "Ek kela fridge mein gaya, aur bola: Bhai, yahan toh bohot thand hai, main toh apni jacket (chhilka) pehen ke hi theek hoon! 🍌🥶",
    "Bacha: Mummy, kela kaisa dikhta hai?\nMummy: Beta, chand jaisa, bas thoda peela aur bohot zyada tasty! 🍌🌙",
    "Chimpu ki GF: Tumhe main zyada pasand hoon ya kela?\nChimpu: Tum...\nGF: Aww sach?\nChimpu: ...tumhare hath mein rakha hua kela! 🍌😂",
    "Kela seb se: Bhai, tera toh juice nikal dete hain, mera toh bas shake banta hai. Main VIP hoon! 🍌😎🍎",
    "Doctor: Tumhara khoon kam ho raha hai.\nChimpu: Khoon ka pata nahi, par kela ekdum bharpoor hai body mein! 🍌🩸",
    "Ek aadmi chhilke par fisal gaya. Kela bola: Kaisa laga mera aashirwad? 🍌🙏",
    "Papa: Beta fail kyun hua?\nChimpu: Question tha 'Define Gravity', maine likha 'Kele ka chhilka + Insaan ka paer = Gravity'. 🍌📚",
    "Dost: Kela khane se dimaag tez hota hai kya?\nChimpu: Pata nahi, par chhilke par pair rakhne se dimaag thikane zaroor aa jata hai! 🍌🧠",
    "Ek bandar ne dusre bandar se pucha: Insaan aur hum mein kya farq hai?\nDusra bandar: Hum kela khakar chhilka fekte hain, wo kela khakar chhilke par chalte hain! 🍌🚶‍♂️",
    "Teacher: Duniya ki sabse khubsurat chiz kya hai?\nChimpu: Adha chhila hua kela, ma'am! 🍌😍",
    "Chimpu: Bhai, kela khane ka sabse accha time kya hai?\nDost: Jab kela muft ka ho! 🍌🤑",
    "Kela aur aam ki race hui. Kela bola: Main haar gaya toh chhilka utar dunga! 🍌🏃‍♂️",
    "Judge: Tumne is aadmi ko kele se kyun mara?\nChimpu: Sir, isne kaha tha ki iska dimaag bandar jaisa hai, maine bas uski diet follow ki! 🍌⚖️",
    "GF: Main udas hoon.\nChimpu: Ek kela kha lo, sab theek ho jayega.\nGF: Main udas hoon, bandar nahi!\nChimpu: Toh aadhi kha lo! 🍌🙄",
    "Ek alien dharti par aaya. Usne kela khaya aur bola: Wow, yahan ke log peele cover mein energy drink bechte hain! 🍌👽",
    "Chimpu ki maa: Beta, roz kela khaya kar, takat aayegi.\nChimpu: Maa, takat toh aa gayi hai, ab ped par chadhne ki aadat jaa nahi rahi! 🍌🐒",
    "Kela tarbooz se: Bhai tu itna mota kyun hai?\nTarbooz: Kyunki meri mummy ne mujhe chhilke mein tight bandh kar nahi rakha! 🍌🍉",
    "Dost: Tujhe itne kele kyun pasand hain?\nChimpu: Kyunki zindagi tedhi ho sakti hai, par kela hamesha meetha hota hai! 🍌💯",
    "Teacher: Sabse meetha phal kaunsa hai?\nChimpu: Jo dushre ke tiffin se churaya hua kela ho! 🍌🎒",
    "Wife: Sunte ho, market se kya laun?\nHusband: Kuch aisi chiz lana jisme vitamin ho, minerals ho, aur mehnat na karni pade.\nWife: Theek hai, main kela le aaungi! 🍌🛒",
    "Kela chila aur bola: Parda nashi ko parda uthne do! 🍌🎭",
    "Chimpu: Doctor, mere pet mein dard hai.\nDoctor: Kya khaya tha?\nChimpu: 12 kele.\nDoctor: Chhilke ke sath?\nChimpu: Nahi, chhilka toh maine padosi ke aangan mein fek diya tha! 🍌🏥",
    "Boss: Tum kaam kyun nahi kar rahe?\nChimpu: Sir, meri battery low hai, kela charge karne gaya hoon! 🍌🔋",
    "Ek kela doosre se: Bhai, insaan bhi ajeeb hain. Humare kapde utar kar khud kehte hain 'Kitna tasty hai'! 🍌😳",
    "GF: Baby, mere liye chand tare tod laao!\nChimpu: Chand ka toh pata nahi, par main tere liye duniya ka sabse lamba kela zaroor laa sakta hoon! 🍌💖",
    "Dost: Kela fridge mein rakhna chahiye ya bahar?\nChimpu: Seedhe pet mein rakhna chahiye bhai! 🍌🤤",
    "Reporter: Aapki lambi umar ka raaz?\nOld Monkey: Subah kela, dopahar kela, raat ko kela... aur sapne mein bhi kela! 🍌👴",
    "Chimpu: Kela ek aisi chiz hai jise bachcha bhi bina daant ke kha sakta hai.\nDost: Aur chhilka?\nChimpu: Wo toh daant walon ke bhi daant tod deta hai! 🍌🦷",
    "Kela aur nimbu mile. Kela bola: Bhai tu hamesha khatta kyun rehta hai?\nNimbu: Aur tu hamesha jacket kyun pehen ke rakhta hai? 🍌🍋",
    "Teacher: Newton ke sir par seb gira toh usne gravity khoji. Agar kela girta toh?\nChimpu: Toh wo kela kha leta aur book likhne ki jagah so jata! 🍌🍎",
    "Mummy: Beta, kele ka chhilka dustbin mein dalo.\nChimpu: Nahi mummy, ye mera anti-theft security system hai. Jo aayega, fisal jayega! 🍌🛡️",
    "Customer: Bhaiya, kela kaisa diya?\nDukandar: 60 rupaye darjan.\nCustomer: Aur cover nikal ke?\nDukandar: Cover nikal ke khayega toh peet dunga! 🍌😠",
    "Chimpu: Mujhe pyaar mein dhoka mila hai.\nDost: Toh ab kya karega?\nChimpu: 2 darjan kela khaunga aur life mein move on karunga! 🍌💔",
    "Doctor: Roz fruit khane se bimaari door rehti hai.\nChimpu: Isliye main roz kela khata hoon, kyunki iska cover koi chhu nahi sakta! 🍌😎",
    "Kela aur pyaz ki dosti hui. Kela bola: Main hamesha fresh dikhta hoon.\nPyaz: Aur main rula deta hoon... jab chhilka utarta hai! 🍌🧅",
    "Teacher: Btao, bandar kele kyun khate hain?\nChimpu: Kyunki unhe pata hai ki Maggi banne mein 2 minute lagte hain aur kela 2 second mein khul jata hai! 🍌🍜",
    "Dost: Bhai, party mein kya laya hai?\nChimpu: Cake, cold drink aur... kela!\nDost: Kela kyun?\nChimpu: Main party ka VIP hoon, mera snack alag hota hai! 🍌🎉",
    "Ek chhilka sadak par pada tha. Kela bola: Dekh bhai, main andar baith kar safar kar raha hoon aur tu road par hai! 🍌🚗",
    "Chimpu: Zindagi jeene ke 2 hi tarike hain.\nDost: Kaunse?\nChimpu: Ya toh maze se kela khao, ya dusro ko kela khilao! 🍌✌️",
    "GF: Mujhe aisi jagah le chalo jahan hara-bhara mahol ho.\nChimpu: Chalo, tumhe kele ke bageeche mein le chalta hoon! 🍌🌴"
]
