# jokes.py

BANANA_JOKES = [
    "Ek kela dusre kele se: Tu itna udas kyun hai?\nDusra kela: Kya karun bhai, main a-kela (akela) hoon na! 🍌😂",
    "Teacher: Kela khane ke kya fayde hain?\nChimpu: Sir, kela khane ke baad chhilke par dushman ko giraya ja sakta hai! 🍌🐒",
    "Customer: 10 rupaye mein ek kela? 5 mein de do!\nDukandar: 5 mein toh sirf chhilka milega.\nCustomer: Ye lo 5 rupaye, chhilka rakh lo aur kela mujhe de do! 🍌😎",
    "Doctor: Roz ek kela khaya karo.\nChimpu: Doctor sahab, main kela khata nahi, kela mera dharam hai! 🍌🐵",
    "Ek Bandar ne sadhu se pucha: Jeevan ka sabse bada sach kya hai?\nSadhu: Beta, kela chahe kitna bhi meetha ho, chhilka utarna hi padta hai! 🍌🤣",
    "Chimpu ki GF: Mere pyaar ki tulna kele se mat karna!\nChimpu: Pata hai jaan, kela ek din kaala pad jata hai par mera pyaar hamesha fresh rahega! 🍌😏",
    "Dost: Bhai tu itna patla kyun ho gaya?\nChimpu: Gym mein trainer ne bola tha 'kela' kha, maine suna 'akela' kha... tab se akele hi kha raha hoon! 🍌😅",
    "Interviewer: Aapki sabse badi kamzori kya hai?\nChimpu: Main kitna bhi gussa hoon, kela dekhte hi pighal jata hoon! 🍌🐒",
    "Teacher: 'Banana' ka plural kya hoga?\nChimpu: Banana shake, sir! 🍌🥤",
    "Police: Tumne chori kyun ki?\nChimpu: Sir, kanoon andha hota hai, par bandar thodi! Samne kela rakha tha, mujhse raha nahi gaya! 🍌🚨",
    "Ek kela fridge mein gaya, aur bola: Bhai, yahan toh bohot thand hai, main toh apni jacket (chhilka) pehen ke hi theek hoon! 🍌🥶",
    "Bacha: Mummy, kela kaisa dikhta hai?\nMummy: Beta, chand jaisa, bas thoda peela aur bohot zyada tasty! 🍌🌙",
    "Chimpu ki GF: Tumhe main zyada pasand hoon ya kela?\nChimpu: Tum...\nGF: Aww sach?\nChimpu: ...tumhare hath mein rakha hua kela! 🍌😂",
    "Kela seb se: Bhai, tera toh juice nikal dete hain, mera toh bas shake banta hai. Main VIP hoon! 🍌😎🍎",
    "Doctor: Tumhara khoon kam ho raha hai.\nChimpu: Khoon ka pata nahi, par kela ekdum bharpoor hai body mein! 🍌🩸",
    "Ek aadmi chhilke par fisal gaya. Kela bola: Kaisa laga mera aashirwad? 🍌🙏",
    "Papa: Beta fail kyun hua?\nChimpu: Question tha 'Define Gravity', maine likha 'Kele ka chhilka + Insaan ka paer = Gravity'. 🍌📚",
    "Dost: Kela khane se dimaag tez hota hai kya?\nChimpu: Pata nahi, par chhilke par pair rakhne se dimaag thikane zaroor aa jata hai! 🍌🧠",
    "Ek bandar ne dusre bandar se pucha: Insaan aur hum mein kya farq hai?\nDusra bandar: Hum kela khakar chhilka fekte hain, wo kela khakar chhilke par chalte hain! 🍌🚶‍♂️",
    "Teacher: Duniya ki sabse khubsurat chiz kya hai?\nChimpu: Adha chhila hua kela, ma'am! 🍌😍",
    "Chimpu: Bhai, kela khane ka sabse accha time kya hai?\nDost: Jab kela muft ka ho! 🍌🤑",
    "Kela aur aam ki race hui. Kela bola: Main haar gaya toh chhilka utar dunga! 🍌🏃‍♂️",
    "Judge: Tumne is aadmi ko kele se kyun mara?\nChimpu: Sir, isne kaha tha ki iska dimaag bandar jaisa hai, maine bas uski diet follow ki! 🍌⚖️",
    "GF: Main udas hoon.\nChimpu: Ek kela kha lo, sab theek ho jayega.\nGF: Main udas hoon, bandar nahi!\nChimpu: Toh aadhi kha lo! 🍌🙄",
    "Ek alien dharti par aaya. Usne kela khaya aur bola: Wow, yahan ke log peele cover mein energy drink bechte hain! 🍌👽",
    "Chimpu ki maa: Beta, roz kela khaya kar, takat aayegi.\nChimpu: Maa, takat toh aa gayi hai, ab ped par chadhne ki aadat jaa nahi rahi! 🍌🐒",
    "Kela tarbooz se: Bhai tu itna mota kyun hai?\nTarbooz: Kyunki meri mummy ne mujhe chhilke mein tight bandh kar nahi rakha! 🍌🍉",
    "Dost: Tujhe itne kele kyun pasand hain?\nChimpu: Kyunki zindagi tedhi ho sakti hai, par kela hamesha meetha hota hai! 🍌💯",
    "Teacher: Sabse meetha phal kaunsa hai?\nChimpu: Jo dushre ke tiffin se churaya hua kela ho! 🍌🎒",
    "Wife: Sunte ho, market se kya laun?\nHusband: Kuch aisi chiz lana jisme vitamin ho, minerals ho, aur mehnat na karni pade.\nWife: Theek hai, main kela le aaungi! 🍌🛒",
    "Kela chila aur bola: Parda nashi ko parda uthne do! 🍌🎭",
    "Chimpu: Doctor, mere pet mein dard hai.\nDoctor: Kya khaya tha?\nChimpu: 12 kele.\nDoctor: Chhilke ke sath?\nChimpu: Nahi, chhilka toh maine padosi ke aangan mein fek diya tha! 🍌🏥",
    "Boss: Tum kaam kyun nahi kar rahe?\nChimpu: Sir, meri battery low hai, kela charge karne gaya hoon! 🍌🔋",
    "Ek kela doosre se: Bhai, insaan bhi ajeeb hain. Humare kapde utar kar khud kehte hain 'Kitna tasty hai'! 🍌😳",
    "GF: Baby, mere liye chand tare tod laao!\nChimpu: Chand ka toh pata nahi, par main tere liye duniya ka sabse lamba kela zaroor laa sakta hoon! 🍌💖",
    "Dost: Kela fridge mein rakhna chahiye ya bahar?\nChimpu: Seedhe pet mein rakhna chahiye bhai! 🍌🤤",
    "Reporter: Aapki lambi umar ka raaz?\nOld Monkey: Subah kela, dopahar kela, raat ko kela... aur sapne mein bhi kela! 🍌👴",
    "Chimpu: Kela ek aisi chiz hai jise bachcha bhi bina daant ke kha sakta hai.\nDost: Aur chhilka?\nChimpu: Wo toh daant walon ke bhi daant tod deta hai! 🍌🦷",
    "Kela aur nimbu mile. Kela bola: Bhai tu hamesha khatta kyun rehta hai?\nNimbu: Aur tu hamesha jacket kyun pehen ke rakhta hai? 🍌🍋",
    "Teacher: Newton ke sir par seb gira toh usne gravity khoji. Agar kela girta toh?\nChimpu: Toh wo kela kha leta aur book likhne ki jagah so jata! 🍌🍎",
    "Mummy: Beta, kele ka chhilka dustbin mein dalo.\nChimpu: Nahi mummy, ye mera anti-theft security system hai. Jo aayega, fisal jayega! 🍌🛡️",
    "Customer: Bhaiya, kela kaisa diya?\nDukandar: 60 rupaye darjan.\nCustomer: Aur cover nikal ke?\nDukandar: Cover nikal ke khayega toh peet dunga! 🍌😠",
    "Chimpu: Mujhe pyaar mein dhoka mila hai.\nDost: Toh ab kya karega?\nChimpu: 2 darjan kela khaunga aur life mein move on karunga! 🍌💔",
    "Doctor: Roz fruit khane se bimaari door rehti hai.\nChimpu: Isliye main roz kela khata hoon, kyunki iska cover koi chhu nahi sakta! 🍌😎",
    "Kela aur pyaz ki dosti hui. Kela bola: Main hamesha fresh dikhta hoon.\nPyaz: Aur main rula deta hoon... jab chhilka utarta hai! 🍌🧅",
    "Teacher: Btao, bandar kele kyun khate hain?\nChimpu: Kyunki unhe pata hai ki Maggi banne mein 2 minute lagte hain aur kela 2 second mein khul jata hai! 🍌🍜",
    "Dost: Bhai, party mein kya laya hai?\nChimpu: Cake, cold drink aur... kela!\nDost: Kela kyun?\nChimpu: Main party ka VIP hoon, mera snack alag hota hai! 🍌🎉",
    "Ek chhilka sadak par pada tha. Kela bola: Dekh bhai, main andar baith kar safar kar raha hoon aur tu road par hai! 🍌🚗",
    "Chimpu: Zindagi jeene ke 2 hi tarike hain.\nDost: Kaunse?\nChimpu: Ya toh maze se kela khao, ya dusro ko kela khilao! 🍌✌️",
    "GF: Mujhe aisi jagah le chalo jahan hara-bhara mahol ho.\nChimpu: Chalo, tumhe kele ke bageeche mein le chalta hoon! 🍌🌴"
    "Chimpu: Bhai, kela aur wifi mein kya similarity hai?\nDost: Kya?\nChimpu: Dono free mil jayein toh log chhodte nahi! 🍌📶",
    "Kela santre se: Bhai tu itna complex kyun hai, chhilne mein itna time lagta hai!\nSantra: Aur tu itna easy hai ki koi bhi aake tera cover utar deta hai! 🍌🍊",
    "Teacher: Sabse jaldi banne wali dish batao?\nChimpu: 2 minute wali Maggi?\nTeacher: Nahi, 2 second wala kela! 🍌⏱️",
    "Ek aadmi kele ke chhilke par fisla, utha, aage chala aur phir dusre chhilke par fisla. Bola: Lo, lagta hai mera replay chal raha hai! 🍌🔄",
    "Chimpu ki GF: Tumhare paas mere liye time nahi hai!\nChimpu: Jaan, jab kela khane ka time hota hai, tab main duniya bhula deta hoon. Tum toh phir bhi second aati ho! 🍌😏",
    "Dost: Agar tumhe ek million dollar mil jaye toh kya karoge?\nChimpu: Duniya ka sabse bada kela kharidunga aur aaram se baith ke khaunga! 🍌💰",
    "Doctor: Apko acidity hai, kela khaya karo.\nChimpu: Doctor sahab, kela toh main khata hoon, par wo pet mein jaane se pehle hi gayab ho jata hai! 🍌🩺",
    "Kela aur angoor ki ladaai hui. Kela bola: Tu toh guchhe mein aata hai, main a-kela hi kafi hoon! 🍌🍇",
    "Wife: Main mayke ja rahi hoon.\nHusband: Theek hai, jate hue darwaza band kar dena.\nWife: Par main naraz hoon!\nHusband: Toh raste mein ek kela khate hue jana, mood theek ho jayega! 🍌🚪",
    "Chimpu: Kela kabhi fail nahi hota.\nDost: Kyun?\nChimpu: Kyunki uska hamesha 'peel' (appeal) strong hota hai! 🍌👨‍⚖️",
    "Teacher: History ka sabse bada invention kya hai?\nChimpu: Jisne pehli baar kele ka chhilka utarna seekha, warna hum use chabate rehte! 🍌📜",
    "Dost: Raat ko kela khana chahiye ya nahi?\nChimpu: Agar kela free ka ho, toh din, raat, subah, sham sab chalta hai! 🍌🌃",
    "Kela nariyal se: Bhai tera cover toh bulletproof hai!\nNariyal: Aur tera cover toh slip-proof ka bilkul opposite hai! 🍌🥥",
    "Chimpu: Mera naya startup hai.\nDost: Kya karega?\nChimpu: Chhilka-free kela bechunga, sidha muh mein delivery! 🍌🚀",
    "Bacha: Papa, kela peela kyun hota hai?\nPapa: Kyunki agar wo laal hota toh log use tamatar samajh kar sabzi mein daal dete! 🍌🍅",
    "Chimpu: Kela ek lota aisi chiz hai jo shuru mein straight hota hai, par badhe hokar tedha ho jata hai.\nDost: Insaan bhi toh aise hi hote hain! 🍌😅",
    "Judge: Tumne is aadmi ki naak kyun todi?\nChimpu: Sir, isne mere kele ko 'overripe' bol diya tha. Yeh meri feelings ka murder tha! 🍌⚖️",
    "GF: Main tumhari life mein kya ahmiyat rakhti hoon?\nChimpu: Tum meri life ki banana shake ho, sweet, thick aur hamesha dil ko thandak dene wali! 🍌🥤",
    "Kela fridge ke andar chillate hue: Arre bahar nikalo mujhe, mera rang kaala pad raha hai thand se! 🍌🥶",
    "Dost: Tu exam mein kela kyun le gaya tha?\nChimpu: Kyunki mujhe energy chahiye thi pass hone ke liye, par teacher ne mujhe hi fail kar diya! 🍌📝",
    "Police: Yeh chhilka sadak par kisne feka?\nChimpu: Sir, yeh gravity ka test ho raha tha, chhilka pass ho gaya! 🍌👮",
    "Ek bandar spaceship mein gaya. Alien ne pucha: Tumhare planet ki sabse advanced technology kya hai?\nBandar ne kela nikal ke bola: Iski packaging dekhi hai? 100% biodegradable! 🍌🛸",
    "Teacher: 'Kela' shabd par ek sentence banao.\nChimpu: 'Kela' itna swadisht tha ki main 'Akela' hi kha gaya! 🍌🤓",
    "Kela aur aalu mile. Kela bola: Main hamesha dessert mein aata hoon.\nAalu: Aur main har sabzi mein set ho jata hoon, tera kya aukat! 🍌🥔",
    "Doctor: Weight kam karna hai toh roz exercise karo.\nChimpu: Main roz kele ke chhilke par fisalta hoon, 10 feet ud ke girta hoon. Yeh exercise nahi toh kya hai? 🍌🏃‍♂️",
    "GF: Tumhare dimaag mein kya chalta rehta hai hamesha?\nChimpu: Bas yahi ki aagle wale kela ka size aur taste kaisa hoga! 🍌🤔",
    "Dost: Kela chhilne mein sabse bada risk kya hai?\nChimpu: Ki koi dusra bandar aake chheen na le! 🍌🐒",
    "Mummy: Beta, mehmaan aane wale hain, kela mat khana.\nChimpu: Tension mat lo mummy, main chhilke sahit kha jaunga, unhe pata hi nahi chalega! 🍌🤫",
    "Kela gusse mein bola: Main sabse meetha hoon, phir bhi log meri sabzi bana dete hain kachha karke! 🍌😠",
    "Chimpu: Zindagi mein do cheezein hamesha fresh honi chahiye.\nDost: Ek toh kela, aur dusri?\nChimpu: Dusra bhi kela hi hai, bhai! 🍌💯",
    "Teacher: Batao, ped (tree) hume kya sikhate hain?\nChimpu: Sir, ped sikhate hain ki kela todne ke liye lamba hona zaroori nahi, bas jump achhi honi chahiye! 🍌🌳",
    "Dost: Bhai, tu kela kha raha hai ya uske sath romance kar raha hai?\nChimpu: Dono, aisi beauty ko time dena padta hai! 🍌😘",
    "Kela aur pyaz ki baat. Kela: Mujhe kaatne par koi nahi rota.\nPyaz: Mujhe toh kaatne wala rota hai, tujhe toh khane wala chhilke par fisal kar rota hai! 🍌🧅",
    "Chimpu ki GF: Mujhe expensive gift chahiye!\nChimpu: Aaj kal kela 80 Rs darjan hai, ek kilo le dun? 🍌💍",
    "Dost: Agar tu PM ban gaya toh pehla rule kya banayega?\nChimpu: Har aadmi ko din mein 3 kele compulsory! Desh fit rahega! 🍌🇮🇳",
    "Judge: Tumhari aakhri khwahish kya hai?\nChimpu: Ek darjan kela aur thoda waqt... aakhri safar meetha hona chahiye! 🍌😢",
    "Teacher: 'Patience' ka example do.\nChimpu: Kachhe kele ka peela hone ka intezaar karna! 🍌🧘‍♂️",
    "Kela aur karela mile. Kela bola: Mera naam tere naam se milta hai, par kaam nahi!\nKarela: Tu meetha ban ke dhoka deta hai, main kadwa ban ke sach bolta hoon! 🍌🥒",
    "Dost: Bhai raat ke 2 baj rahe hain, kahan ja raha hai?\nChimpu: Kitchen mein. Fridge mein ek kela pada hai, mujhe neend mein awaaz de raha hai! 🍌🚶‍♂️",
    "GF: Tum mujhse kitna pyaar karte ho?\nChimpu: Utna hi jitna ek bandar kele se karta hai, yaani 'anant' (infinite)! 🍌❤️",
    "Ek din kele ne bhagwan se pucha: Mujhe itna achha kyun banaya?\nBhagwan: Taki Chimpu jaise bandar duniya mein khush reh sakein! 🍌🙏",
    "Doctor: Roz 5000 kadam chalo.\nChimpu: Agar aage kele ki dukan ho, toh main 10,000 kadam bhi chal lunga! 🍌👟",
    "Kela seb se: Main seedha paida nahi hota, meri thodi akad hai!\nSeb: Par tu itna jaldi gal kyu jata hai bhai? 🍌🍎",
    "Teacher: Kela ek complete food hai.\nChimpu: Haan sir, khane ke baad chhilke se entertainment (fisalna) bhi free milta hai! 🍌🎬",
    "Dost: Bhai tu sad kyun hai?\nChimpu: Maine raat ko ek sapna dekha, samne bahut saare kele the...\nDost: Toh khush ho ja!\nChimpu: Arey, sapne mein mere daant hi nahi the! 🍌😭",
    "Wife: Suno, agar main kela hoti toh tum kya karte?\nHusband: Main tujhe chhil kar kachre ke dabbe mein fenk deta! 🍌🗑️ (P.S. Husband 2 din se bhookha hai)",
    "Chimpu: Bhai, kela khane ka sabse bada side effect kya hai?\nDost: Kya?\nChimpu: Log tumhe bandar samajhne lagte hain! 🍌🐒",
    "Ek kela gya gym. Trainer: Body banani hai?\nKela: Nahi, thoda tight hona hai, log 'pila-pila' bolte hain! 🍌💪",
    "Teacher: Btao, Vitamin B kismein hota hai?\nChimpu: B for Banana, sir! B for Bandar, B for Best fruit in the world! 🍌🏆",
    "Dost: Kela aur aam mein kya behtar hai?\nChimpu: Kela. Aam khane ke baad hath dhone padte hain, kela aap smart logo ki tarah ek haath se kha sakte ho! 🍌😎"
]

