# jokes.py

BANANA_JOKES = [
    "Ek kela dusre kele se: Tu itna udas kyun hai?\nDusra kela: Kya karun bhai, main a-kela (akela) hoon na! 🍌😂",
    "Teacher: Kela khane ke kya fayde hain?\nChimpu: Sir, kela khane ke baad chhilke par dushman ko giraya ja sakta hai! 🍌🐒",
    "Customer: 10 rupaye mein ek kela? 5 mein de do!\nDukandar: 5 mein toh sirf chhilka milega.\nCustomer: Ye lo 5 rupaye, chhilka rakh lo aur kela mujhe de do! 🍌😎",
    "Doctor: Roz ek kela khaya karo.\nChimpu: Doctor sahab, main kela khata nahi, kela mera dharam hai! 🍌🐵",
    "Ek Bandar ne sadhu se pucha: Jeevan ka sabse bada sach kya hai?\nSadhu: Beta, kela chahe kitna bhi meetha ho, chhilka utarna hi padta hai! 🍌🤣",
    "Chimpu ki GF: Mere pyaar ki tulna kele se mat karna!\nChimpu: Pata hai jaan, kela ek din kaala pad jata hai par mera pyaar hamesha fresh rahega! 🍌😏",
    "Dost: Bhai tu itna patla kyun ho gaya?\nChimpu: Gym mein trainer ne bola tha 'kela' kha, maine suna 'akela' kha... tab se akele hi kha raha hoon! 🍌😅",
    "Interviewer: Aapki sabse badi kamzori kya hai?\nChimpu: Main kitna bhi gussa hoon, kela dekhte hi pighal jata hoon! 🍌🐒",
    "Teacher: 'Banana' ka plural kya hoga?\nChimpu: Banana shake, sir! 🍌🥤",
    "Police: Tumne chori kyun ki?\nChimpu: Sir, kanoon andha hota hai, par bandar thodi! Samne kela rakha tha, mujhse raha nahi gaya! 🍌🚨",
    "Ek kela fridge mein gaya, aur bola: Bhai, yahan toh bohot thand hai, main toh apni jacket (chhilka) pehen ke hi theek hoon! 🍌🥶",
    "Bacha: Mummy, kela kaisa dikhta hai?\nMummy: Beta, chand jaisa, bas thoda peela aur bohot zyada tasty! 🍌🌙",
    "Chimpu ki GF: Tumhe main zyada pasand hoon ya kela?\nChimpu: Tum...\nGF: Aww sach?\nChimpu: ...tumhare hath mein rakha hua kela! 🍌😂",
    "Kela seb se: Bhai, tera toh juice nikal dete hain, mera toh bas shake banta hai. Main VIP hoon! 🍌😎🍎",
    "Doctor: Tumhara khoon kam ho raha hai.\nChimpu: Khoon ka pata nahi, par kela ekdum bharpoor hai body mein! 🍌🩸",
    "Ek aadmi chhilke par fisal gaya. Kela bola: Kaisa laga mera aashirwad? 🍌🙏",
    "Papa: Beta fail kyun hua?\nChimpu: Question tha 'Define Gravity', maine likha 'Kele ka chhilka + Insaan ka paer = Gravity'. 🍌📚",
    "Dost: Kela khane se dimaag tez hota hai kya?\nChimpu: Pata nahi, par chhilke par pair rakhne se dimaag thikane zaroor aa jata hai! 🍌🧠",
    "Ek bandar ne dusre bandar se pucha: Insaan aur hum mein kya farq hai?\nDusra bandar: Hum kela khakar chhilka fekte hain, wo kela khakar chhilke par chalte hain! 🍌🚶‍♂️",
    "Teacher: Duniya ki sabse khubsurat chiz kya hai?\nChimpu: Adha chhila hua kela, ma'am! 🍌😍",
    "Chimpu: Bhai, kela khane ka sabse accha time kya hai?\nDost: Jab kela muft ka ho! 🍌🤑",
    "Kela aur aam ki race hui. Kela bola: Main haar gaya toh chhilka utar dunga! 🍌🏃‍♂️",
    "Judge: Tumne is aadmi ko kele se kyun mara?\nChimpu: Sir, isne kaha tha ki iska dimaag bandar jaisa hai, maine bas uski diet follow ki! 🍌⚖️",
    "GF: Main udas hoon.\nChimpu: Ek kela kha lo, sab theek ho jayega.\nGF: Main udas hoon, bandar nahi!\nChimpu: Toh aadhi kha lo! 🍌🙄",
    "Ek alien dharti par aaya. Usne kela khaya aur bola: Wow, yahan ke log peele cover mein energy drink bechte hain! 🍌👽",
    "Chimpu ki maa: Beta, roz kela khaya kar, takat aayegi.\nChimpu: Maa, takat toh aa gayi hai, ab ped par chadhne ki aadat jaa nahi rahi! 🍌🐒",
    "Kela tarbooz se: Bhai tu itna mota kyun hai?\nTarbooz: Kyunki meri mummy ne mujhe chhilke mein tight bandh kar nahi rakha! 🍌🍉",
    "Dost: Tujhe itne kele kyun pasand hain?\nChimpu: Kyunki zindagi tedhi ho sakti hai, par kela hamesha meetha hota hai! 🍌💯",
    "Teacher: Sabse meetha phal kaunsa hai?\nChimpu: Jo dushre ke tiffin se churaya hua kela ho! 🍌🎒",
    "Wife: Sunte ho, market se kya laun?\nHusband: Kuch aisi chiz lana jisme vitamin ho, minerals ho, aur mehnat na karni pade.\nWife: Theek hai, main kela le aaungi! 🍌🛒",
    "Kela chila aur bola: Parda nashi ko parda uthne do! 🍌🎭",
    "Chimpu: Doctor, mere pet mein dard hai.\nDoctor: Kya khaya tha?\nChimpu: 12 kele.\nDoctor: Chhilke ke sath?\nChimpu: Nahi, chhilka toh maine padosi ke aangan mein fek diya tha! 🍌🏥",
    "Boss: Tum kaam kyun nahi kar rahe?\nChimpu: Sir, meri battery low hai, kela charge karne gaya hoon! 🍌🔋",
    "Ek kela doosre se: Bhai, insaan bhi ajeeb hain. Humare kapde utar kar khud kehte hain 'Kitna tasty hai'! 🍌😳",
    "GF: Baby, mere liye chand tare tod laao!\nChimpu: Chand ka toh pata nahi, par main tere liye duniya ka sabse lamba kela zaroor laa sakta hoon! 🍌💖",
    "Dost: Kela fridge mein rakhna chahiye ya bahar?\nChimpu: Seedhe pet mein rakhna chahiye bhai! 🍌🤤",
    "Reporter: Aapki lambi umar ka raaz?\nOld Monkey: Subah kela, dopahar kela, raat ko kela... aur sapne mein bhi kela! 🍌👴",
    "Chimpu: Kela ek aisi chiz hai jise bachcha bhi bina daant ke kha sakta hai.\nDost: Aur chhilka?\nChimpu: Wo toh daant walon ke bhi daant tod deta hai! 🍌🦷",
    "Kela aur nimbu mile. Kela bola: Bhai tu hamesha khatta kyun rehta hai?\nNimbu: Aur tu hamesha jacket kyun pehen ke rakhta hai? 🍌🍋",
    "Teacher: Newton ke sir par seb gira toh usne gravity khoji. Agar kela girta toh?\nChimpu: Toh wo kela kha leta aur book likhne ki jagah so jata! 🍌🍎",
    "Mummy: Beta, kele ka chhilka dustbin mein dalo.\nChimpu: Nahi mummy, ye mera anti-theft security system hai. Jo aayega, fisal jayega! 🍌🛡️",
    "Customer: Bhaiya, kela kaisa diya?\nDukandar: 60 rupaye darjan.\nCustomer: Aur cover nikal ke?\nDukandar: Cover nikal ke khayega toh peet dunga! 🍌😠",
    "Chimpu: Mujhe pyaar mein dhoka mila hai.\nDost: Toh ab kya karega?\nChimpu: 2 darjan kela khaunga aur life mein move on karunga! 🍌💔",
    "Doctor: Roz fruit khane se bimaari door rehti hai.\nChimpu: Isliye main roz kela khata hoon, kyunki iska cover koi chhu nahi sakta! 🍌😎",
    "Kela aur pyaz ki dosti hui. Kela bola: Main hamesha fresh dikhta hoon.\nPyaz: Aur main rula deta hoon... jab chhilka utarta hai! 🍌🧅",
    "Teacher: Btao, bandar kele kyun khate hain?\nChimpu: Kyunki unhe pata hai ki Maggi banne mein 2 minute lagte hain aur kela 2 second mein khul jata hai! 🍌🍜",
    "Dost: Bhai, party mein kya laya hai?\nChimpu: Cake, cold drink aur... kela!\nDost: Kela kyun?\nChimpu: Main party ka VIP hoon, mera snack alag hota hai! 🍌🎉",
    "Ek chhilka sadak par pada tha. Kela bola: Dekh bhai, main andar baith kar safar kar raha hoon aur tu road par hai! 🍌🚗",
    "Chimpu: Zindagi jeene ke 2 hi tarike hain.\nDost: Kaunse?\nChimpu: Ya toh maze se kela khao, ya dusro ko kela khilao! 🍌✌️",
    "GF: Mujhe aisi jagah le chalo jahan hara-bhara mahol ho.\nChimpu: Chalo, tumhe kele ke bageeche mein le chalta hoon! 🍌🌴"
    "Chimpu: Bhai, kela aur wifi mein kya similarity hai?\nDost: Kya?\nChimpu: Dono free mil jayein toh log chhodte nahi! 🍌📶",
    "Kela santre se: Bhai tu itna complex kyun hai, chhilne mein itna time lagta hai!\nSantra: Aur tu itna easy hai ki koi bhi aake tera cover utar deta hai! 🍌🍊",
    "Teacher: Sabse jaldi banne wali dish batao?\nChimpu: 2 minute wali Maggi?\nTeacher: Nahi, 2 second wala kela! 🍌⏱️",
    "Ek aadmi kele ke chhilke par fisla, utha, aage chala aur phir dusre chhilke par fisla. Bola: Lo, lagta hai mera replay chal raha hai! 🍌🔄",
    "Chimpu ki GF: Tumhare paas mere liye time nahi hai!\nChimpu: Jaan, jab kela khane ka time hota hai, tab main duniya bhula deta hoon. Tum toh phir bhi second aati ho! 🍌😏",
    "Dost: Agar tumhe ek million dollar mil jaye toh kya karoge?\nChimpu: Duniya ka sabse bada kela kharidunga aur aaram se baith ke khaunga! 🍌💰",
    "Doctor: Apko acidity hai, kela khaya karo.\nChimpu: Doctor sahab, kela toh main khata hoon, par wo pet mein jaane se pehle hi gayab ho jata hai! 🍌🩺",
    "Kela aur angoor ki ladaai hui. Kela bola: Tu toh guchhe mein aata hai, main a-kela hi kafi hoon! 🍌🍇",
    "Wife: Main mayke ja rahi hoon.\nHusband: Theek hai, jate hue darwaza band kar dena.\nWife: Par main naraz hoon!\nHusband: Toh raste mein ek kela khate hue jana, mood theek ho jayega! 🍌🚪",
    "Chimpu: Kela kabhi fail nahi hota.\nDost: Kyun?\nChimpu: Kyunki uska hamesha 'peel' (appeal) strong hota hai! 🍌👨‍⚖️",
    "Teacher: History ka sabse bada invention kya hai?\nChimpu: Jisne pehli baar kele ka chhilka utarna seekha, warna hum use chabate rehte! 🍌📜",
    "Dost: Raat ko kela khana chahiye ya nahi?\nChimpu: Agar kela free ka ho, toh din, raat, subah, sham sab chalta hai! 🍌🌃",
    "Kela nariyal se: Bhai tera cover toh bulletproof hai!\nNariyal: Aur tera cover toh slip-proof ka bilkul opposite hai! 🍌🥥",
    "Chimpu: Mera naya startup hai.\nDost: Kya karega?\nChimpu: Chhilka-free kela bechunga, sidha muh mein delivery! 🍌🚀",
    "Bacha: Papa, kela peela kyun hota hai?\nPapa: Kyunki agar wo laal hota toh log use tamatar samajh kar sabzi mein daal dete! 🍌🍅",
    "Chimpu: Kela ek lota aisi chiz hai jo shuru mein straight hota hai, par badhe hokar tedha ho jata hai.\nDost: Insaan bhi toh aise hi hote hain! 🍌😅",
    "Judge: Tumne is aadmi ki naak kyun todi?\nChimpu: Sir, isne mere kele ko 'overripe' bol diya tha. Yeh meri feelings ka murder tha! 🍌⚖️",
    "GF: Main tumhari life mein kya ahmiyat rakhti hoon?\nChimpu: Tum meri life ki banana shake ho, sweet, thick aur hamesha dil ko thandak dene wali! 🍌🥤",
    "Kela fridge ke andar chillate hue: Arre bahar nikalo mujhe, mera rang kaala pad raha hai thand se! 🍌🥶",
    "Dost: Tu exam mein kela kyun le gaya tha?\nChimpu: Kyunki mujhe energy chahiye thi pass hone ke liye, par teacher ne mujhe hi fail kar diya! 🍌📝",
    "Police: Yeh chhilka sadak par kisne feka?\nChimpu: Sir, yeh gravity ka test ho raha tha, chhilka pass ho gaya! 🍌👮",
    "Ek bandar spaceship mein gaya. Alien ne pucha: Tumhare planet ki sabse advanced technology kya hai?\nBandar ne kela nikal ke bola: Iski packaging dekhi hai? 100% biodegradable! 🍌🛸",
    "Teacher: 'Kela' shabd par ek sentence banao.\nChimpu: 'Kela' itna swadisht tha ki main 'Akela' hi kha gaya! 🍌🤓",
    "Kela aur aalu mile. Kela bola: Main hamesha dessert mein aata hoon.\nAalu: Aur main har sabzi mein set ho jata hoon, tera kya aukat! 🍌🥔",
    "Doctor: Weight kam karna hai toh roz exercise karo.\nChimpu: Main roz kele ke chhilke par fisalta hoon, 10 feet ud ke girta hoon. Yeh exercise nahi toh kya hai? 🍌🏃‍♂️",
    "GF: Tumhare dimaag mein kya chalta rehta hai hamesha?\nChimpu: Bas yahi ki aagle wale kela ka size aur taste kaisa hoga! 🍌🤔",
    "Dost: Kela chhilne mein sabse bada risk kya hai?\nChimpu: Ki koi dusra bandar aake chheen na le! 🍌🐒",
    "Mummy: Beta, mehmaan aane wale hain, kela mat khana.\nChimpu: Tension mat lo mummy, main chhilke sahit kha jaunga, unhe pata hi nahi chalega! 🍌🤫",
    "Kela gusse mein bola: Main sabse meetha hoon, phir bhi log meri sabzi bana dete hain kachha karke! 🍌😠",
    "Chimpu: Zindagi mein do cheezein hamesha fresh honi chahiye.\nDost: Ek toh kela, aur dusri?\nChimpu: Dusra bhi kela hi hai, bhai! 🍌💯",
    "Teacher: Batao, ped (tree) hume kya sikhate hain?\nChimpu: Sir, ped sikhate hain ki kela todne ke liye lamba hona zaroori nahi, bas jump achhi honi chahiye! 🍌🌳",
    "Dost: Bhai, tu kela kha raha hai ya uske sath romance kar raha hai?\nChimpu: Dono, aisi beauty ko time dena padta hai! 🍌😘",
    "Kela aur pyaz ki baat. Kela: Mujhe kaatne par koi nahi rota.\nPyaz: Mujhe toh kaatne wala rota hai, tujhe toh khane wala chhilke par fisal kar rota hai! 🍌🧅",
    "Chimpu ki GF: Mujhe expensive gift chahiye!\nChimpu: Aaj kal kela 80 Rs darjan hai, ek kilo le dun? 🍌💍",
    "Dost: Agar tu PM ban gaya toh pehla rule kya banayega?\nChimpu: Har aadmi ko din mein 3 kele compulsory! Desh fit rahega! 🍌🇮🇳",
    "Judge: Tumhari aakhri khwahish kya hai?\nChimpu: Ek darjan kela aur thoda waqt... aakhri safar meetha hona chahiye! 🍌😢",
    "Teacher: 'Patience' ka example do.\nChimpu: Kachhe kele ka peela hone ka intezaar karna! 🍌🧘‍♂️",
    "Kela aur karela mile. Kela bola: Mera naam tere naam se milta hai, par kaam nahi!\nKarela: Tu meetha ban ke dhoka deta hai, main kadwa ban ke sach bolta hoon! 🍌🥒",
    "Dost: Bhai raat ke 2 baj rahe hain, kahan ja raha hai?\nChimpu: Kitchen mein. Fridge mein ek kela pada hai, mujhe neend mein awaaz de raha hai! 🍌🚶‍♂️",
    "GF: Tum mujhse kitna pyaar karte ho?\nChimpu: Utna hi jitna ek bandar kele se karta hai, yaani 'anant' (infinite)! 🍌❤️",
    "Ek din kele ne bhagwan se pucha: Mujhe itna achha kyun banaya?\nBhagwan: Taki Chimpu jaise bandar duniya mein khush reh sakein! 🍌🙏",
    "Doctor: Roz 5000 kadam chalo.\nChimpu: Agar aage kele ki dukan ho, toh main 10,000 kadam bhi chal lunga! 🍌👟",
    "Kela seb se: Main seedha paida nahi hota, meri thodi akad hai!\nSeb: Par tu itna jaldi gal kyu jata hai bhai? 🍌🍎",
    "Teacher: Kela ek complete food hai.\nChimpu: Haan sir, khane ke baad chhilke se entertainment (fisalna) bhi free milta hai! 🍌🎬",
    "Dost: Bhai tu sad kyun hai?\nChimpu: Maine raat ko ek sapna dekha, samne bahut saare kele the...\nDost: Toh khush ho ja!\nChimpu: Arey, sapne mein mere daant hi nahi the! 🍌😭",
    "Wife: Suno, agar main kela hoti toh tum kya karte?\nHusband: Main tujhe chhil kar kachre ke dabbe mein fenk deta! 🍌🗑️ (P.S. Husband 2 din se bhookha hai)",
    "Chimpu: Bhai, kela khane ka sabse bada side effect kya hai?\nDost: Kya?\nChimpu: Log tumhe bandar samajhne lagte hain! 🍌🐒",
    "Ek kela gya gym. Trainer: Body banani hai?\nKela: Nahi, thoda tight hona hai, log 'pila-pila' bolte hain! 🍌💪",
    "Teacher: Btao, Vitamin B kismein hota hai?\nChimpu: B for Banana, sir! B for Bandar, B for Best fruit in the world! 🍌🏆",
    "Dost: Kela aur aam mein kya behtar hai?\nChimpu: Kela. Aam khane ke baad hath dhone padte hain, kela aap smart logo ki tarah ek haath se kha sakte ho! 🍌😎"
    "Dost: Bhai Valentine's Day pe kya kar raha hai?\nMain: Kela khaunga, kyunki main A-Kela hoon! 🍌😎💔",
    "Teacher: Batao, ped se kya girta hai?\nPappu: Kela!\nTeacher: Bewakoof, seb (apple) girta hai, Newton ko wahi mila tha!\nPappu: Newton lucky tha, kela girta toh chatni ban jati! 🤣🐒",
    "Doctor: Tumhara weight badh raha hai, kela khana band karo.\nPatient: Par kyon?\nDoctor: Kyunki kela kabhi 'akela' nahi aata, motapa sath lata hai! 🍌😜",
    "Monkey 1: Insaan humse kitne peeche hain yaar.\nMonkey 2: Kaise?\nMonkey 1: Hum kela chheel kar khate hain, aur wo kela chheel kar chilke pe fisal jaate hain! 🐒🍌😂",
    "Ek sad boy ne dukandar se pucha: Bhai, pyaar milega?\nDukandar: Nahi bhai, bas kela milega, aur wo bhi darjan ke hisaab se. 🍌🤣",
    "Kela hamesha guchhe mein kyun hota hai?\nKyunki use bhi pata hai aaj kal 'akela' rehna kitna mushkil hai! 🍌😂👫",
    "Santa: Yaar Banta, main akela mehsoos kar raha hoon.\nBanta: Toh a-kela mat kha, do-kele kha le! 🍌🍌😜",
    "Gym bro: Bhai pre-workout mein kya leta hai?\nMe: Ek kela aur apni ex ki yaadein... dono heart-rate badha dete hain! 🍌🏋️‍♂️😂",
    "Patient: Doctor sahab, kya main kela kha sakta hoon?\nDoctor: Haan, par chilka utaar kar! 🍌👨‍⚕️🤣",
    "Gym Trainer: Muscle building ke liye kela sabse best hai.\nPappu: Tabhi toh bandar sabse zyada fit hote hain! 🐒🍌😎",
    "Teacher: 'A' for Apple, 'B' for?\nPappu: 'B' for Bahut saara kela! 🍌🤣",
    "Teacher: Kela aur aam mein kya farq hai?\nChintu: Aam choos ke khate hain, kela chheel ke, aur dono mein maza aata hai! 🥭🍌😜",
    "Teacher: Aisa kaunsa phal hai jismein beej nahi hota?\nPappu: Kela!\nTeacher: Very good, aur kuch?\nPappu: Plastic ka seb! 🍎🍌😂",
    "Teacher: Newton ke sarr pe apple gira toh Gravity mili. Kela girta toh kya hota?\nStudent: Bandar aake kha jata aur physics aasan ho jati! 🐒🍌📚🤣",
    "Principal: Tum roz tiffin mein kela kyun laate ho?\nChintu: Kyunki mummy kehti hain kela dimag tej karta hai, aur mera dimag bandar jaisa hai! 🐒🍌😂",
    "Ek bandar sad tha. Dusre ne pucha: Kya hua bhai?\nPehla bandar: Aaj insaan ne mujhe kela dikha kar khud kha liya! 🐒🍌😭",
    "Bandar ki sabse pasandeeda gaadi kaunsi hai?\nKela-rola (Corolla)! 🚗🍌🐒😂",
    "Sher: Jungle ka raja main hoon!\nBandar: Haan toh? Kela toh mere paas hi hai! 🦁🐒🍌🤣",
    "Bhaloo: Bhai tu itna chust kaise rehta hai?\nBandar: Secret hai boss... Kela power! 🍌😎🐒",
    "Ek bandar ne bhagwan se pucha: Mujhe insaan kab banaoge?\nBhagwan: Jab tu chilka dustbin mein dalna shuru karega! 🐒🍌🗑️😂",
    "Aadmi 1: Aaj kela kha ke chilka road pe phenk diya.\nAadmi 2: Phir?\nAadmi 1: Phir kya, aage jaa ke usi pe slip hoke apna hi popat ho gaya! 🍌🤕🤣",
    "Kela khane se zyada maza kis mein hai?\nDushman ko kela khila kar uska chilka uske raste mein rakhne mein! 🍌😈😂",
    "Wife: Ye kiske chilke pade hain zameen par?\nHusband: Main kela kha raha tha.\nWife: Par tum toh abhi chalke aaye?\nHusband: Haan, chilke ke sahare slide karke! 🍌⛸️😂",
    "Boss: Office late kyun aaye?\nEmployee: Sir, raste mein kele ka chilka tha.\nBoss: Toh?\nEmployee: Main fisla nahi, isliye disappoint hoke wapas ghar chala gaya tha! 🍌🤦‍♂️🤣",
    "Doctor: Haddi kaise tooti?\nPatient: Kele ke chilke pe fisal gaya.\nDoctor: Toh dhyan kyu nahi rakha?\nPatient: Chilka naya tha, mujhe laga fislega nahi! 🍌🦴😂",
    "Wife: Suno ji, bazaar se aate hue aam le aana.\nHusband: Aur aam na mile toh?\nWife: Toh kela le aana, par aana zaroor varna akela kar dungi! 🍌😠😂",
    "Wife: Main tumhare liye kya banau?\nHusband: Ek kaam kar, kela le aa.\nWife: Kyun?\nHusband: Kyunki usme mujhe tumhari cooking skills nahi jhelni padegi! 🍌👨‍🍳🤣",
    "Husband: Kela laye huye 3 din ho gaye, kaale ho rahe hain.\nWife: Toh unhe thoda Fair & Lovely laga do! 🍌🙎‍♀️😂",
    "Wife: Mera vajan badh gaya hai, diet pe hoon.\nHusband: Kela kha!\nWife: Usse patli ho jaungi?\nHusband: Nahi, bas mooh band rahega kuch der! 🍌🤐🤣",
    "Santa hawai jahaz mein kela kha raha tha.\nAir hostess: Sir chilka yahan mat fenkiye.\nSanta: Toh kya khidki khol ke baahar fenku? 🍌✈️🤣",
    "Santa: Bhai, maine 1 darjan kela liya, par 11 hi nikle.\nBanta: Dusra kahan gaya?\nSanta: Wo maine dukandar ke saamne hi test kar liya tha! 🍌🤷‍♂️🤣",
    "Santa: Bhai tera business kaisa chal raha hai?\nBanta: Ekdum kele jaisa.\nSanta: Matlab meetha?\nBanta: Nahi, log chilka utaar ke kha jaate hain! 🍌📉😂",
    "Banta dukandar se: Bhai aadha kela milega?\nDukandar: Aadha kela nahi milta.\nBanta: Toh aesa kar, ek pura de, main aadha yahin chhod dunga! 🍌🤦‍♂️😂",
    "Santa: Mujhe raat ko neend nahi aati.\nBanta: Sone se pehle kela kha liya kar.\nSanta: Usse kya hoga?\nBanta: Pet bhar jayega toh dimaag sone dega! 🍌😴🤣",
    "Boy: Will you be my girlfriend?\nGirl: I am committed.\nBoy: Chalo koi nahi, main kal bhi 'a-kela' tha, aaj bhi 'a-kela' hoon! 🍌💔😂",
    "Zindagi mein agar kuch ban-na hai toh kela bano.\nLog pasand toh karenge, aur sasta bhi rahoge! 🍌🤑😂",
    "Dost 1: Goa chalte hain sab milke.\nDost 2: Mera budget nahi hai, main akela yahan theek hoon.\nDost 1: Akela theek hai, par hum wahan bahut saara 'kela' khaenge! 🍌🏖️🤣",
    "Kela aam se kyun jalta hai?\nKyunki aam ko log chus-chus ke khate hain, aur kele ko kaat dete hain! 🍌🔪🥭😂",
    "Zindagi ek kele ki tarah hai.\nKabhi meethi hoti hai, aur kabhi chilke pe fisal ke lag jati hai! 🍌🤕😂",
    "Bhikari: Bhagwan ke naam pe kuch de de baba.\nAadmi: Ye le kela kha le.\nBhikari: Bhai cash de, kela toh main khud kharid lunga! 🍌💸🤣",
    "Chintu: Bhai mujhe akele darr lagta hai.\nPappu: Toh kela kha aur darr bhaga! 🍌👻😂",
    "Girlfriend: Tum mere liye kya kar sakte ho?\nBoyfriend: Main tere liye roz 2 darjan kela kha sakta hoon!\nGirlfriend: Isme kya badi baat hai?\nBoyfriend: Meri monkey-giri ka saboot hai ye! 🐒🍌😂",
    "Pappu: Bhai ye kela kala kyun ho gaya hai?\nDukandar: Dhoop mein zyada ghoom liya hoga, sunscreen nahi lagaya! 🍌☀️🤣",
    "Salesman: Sir ye kela bilkul fresh hai.\nCustomer: Fresh? Ispe toh daag hain!\nSalesman: Sir ye kela experienced hai, isne duniya dekhi hai! 🍌🌍😂",
    "Customer: Bhai 1 darjan kela dena, par saare seedhe hone chahiye.\nDukandar: Bhai kela hai, engineering ka scale thodi! 🍌📏🤣",
    "Aadmi 1: Aaj maine sapne mein 100 kele khaye.\nAadmi 2: Fir kya hua?\nAadmi 1: Subah utha toh pet dard ho raha tha! 🍌🛌😂",
    "Kele ne aam se pucha: Tu itna expensive kyun hai?\nAam: Kyunki meri marketing achi hai, aur tera chilka muft mein fisalwata hai! 🥭🍌📈😂",
    "Son: Papa mujhe ek iPhone chahiye.\nPapa: Ye le kela kha.\nSon: Kela kyun?\nPapa: Kyunki 'Apple' toh apne budget ke bahar hai! 🍏🍌📱🤣",
    "Dost: Bhai kal party mein kyun nahi aaya?\nMe: Yaar meri bike ka tyre puncture ho gaya tha.\nDost: Toh paidal aa jata.\nMe: Paidal aata toh raste mein kele ka chilka mera wait kar raha tha! 🍌🚶‍♂️😂",
    "Pappu: Mummy, aaj school mein teacher ne mujhe kela banaya!\nMummy: Kela banaya? Wo kaise?\nPappu: Sabke samne mera chilka utaar diya! 🍌😳🤣",
    "Police: Tumne is aadmi ko kyun mara?\nChor: Sir, isne mujhe kela dikha ke bhagaya!\nPolice: Toh?\nChor: Main bandar thodi hoon jo kele ke liye daudunga! 🍌🐒🚔😂",
    "Raju: Kela khane se stamina badhta hai.\nShyam: Haan, aur chilke pe chalne se speed! 🍌🏃‍♂️🤣",
    "Wife: Aaj raat khane mein kya khaaoge?\nHusband: Kuch meetha aur healthy ho jaye.\nWife: Theek hai, main dho kar kela table pe rakh deti hoon! 🍌🍽️😂",
    "Doctor: Aapko roz subah jogging karni chahiye.\nPatient: Par raste mein bahut saare kele ke chilke hote hain.\nDoctor: Toh shoes pehan ke fisla karo, safety zaroori hai! 🍌👟🤣",
    "Interviewer: Tumhari sabse badi strength kya hai?\nCandidate: Main bina haath lagaye kela kha sakta hoon!\nInterviewer: You are hired for our monkey department! 🐒🍌👔😂",
    "Dost: Tere phone ka password kya hai?\nMe: KELA123.\nDost: Aisa kyun?\nMe: Kyunki koi isse hack nahi kar payega, sab fisal jayenge! 🍌🔐🤣",
    "Banta: Yaar, main soch raha hoon kela ka business shuru karu.\nSanta: Mat kar bhai.\nBanta: Kyun?\nSanta: Tu toh saare kele khud hi kha jayega! 🍌💼😂",
    "Kela aur Santra race laga rahe the.\nSantra aage nikal gaya.\nKele ne apna chilka aage fenk diya, Santra fisal gaya. Kela wins! 🍌🍊🏁😂",
    "Teacher: Tell me a sentence using the word 'Kela'.\nStudent: Kal 'akela' aaya tha, aaj 'akela' jaunga! 🍌📜🤣",
    "Pappu: Bhai, aam ko phalon ka raja kehte hain, toh kela kya hai?\nChintu: Kela phalon ka 'joker' hai, hamesha chilke se hasata hai! 🍌🤡😂",
    "Aadmi: Doctor, mujhe lagta hai main ek kela hoon.\nDoctor: Chinta mat karo, let jao aur apni problem 'chheel' ke batao! 🍌🛋️🤣",
    "Mummy: Beta, breakfast mein kela kha lo.\nBeta: Mummy, roz roz kela? Main koi Minion hoon kya? 🍌👓😂",
    "Dost 1: Agar tujhe ek superpower milti toh tu kya mangta?\nDost 2: Duniya ke saare kele gayab kar deta!\nDost 1: Kyun?\nDost 2: Taaki bandar insaano ki respect karein! 🐒🍌🦸‍♂️🤣",
    "Santa: Aaj maine ek naya aavishkar kiya hai!\nBanta: Kya?\nSanta: Ek aesa kela jisme beej hote hain!\nBanta: Phir use khayega kaun? 🍌🤯😂",
    "Boy: Main tere liye chand tare tod launga!\nGirl: Chand tare chhod, pehle dukaan se ek darjan kela toh le aa! 🍌🌌🤣",
    "Kela: Log mujhe kitna pyar karte hain.\nSeb: Haan, par beemari mein mujhe hi yaad karte hain! 🍌🍎🤒😂",
    "Pappu: Bhai, train mein kela kyu bechte hain?\nDost: Taki safar mein koi 'akela' bore na ho! 🍌🚆🤣",
    "Teacher: Jo bacha sabse pehle answer dega use inaam milega.\nStudent: Kya milega?\nTeacher: Ek kela!\nStudent: Sir hum bache hain, bandar nahi! 🐒🍌🎁😂",
    "Patient: Doctor, mere pet mein dard hai.\nDoctor: Kya khaya tha?\nPatient: 10 kele.\nDoctor: Toh dard toh hoga hi, bandar ka quota kha gaye tum! 🍌🐒💊🤣",
    "Aadmi 1: Aajkal kela kitna mehnga ho gaya hai.\nAadmi 2: Haan bhai, ab toh bandar bhi loan leke kela khate hain! 🍌🏦🐒😂",
    "Wife: Tumhari car aage piche kyu ho rahi hai?\nHusband: Petrol khatam ho gaya tha, car mein kela daal diya!\nWife: Bewakoof, car kela thodi khati hai.\nHusband: Tabhi toh fisal rahi hai! 🍌🚗🤣",
    "Bhikari: Babu ji, 2 din se bhukha hoon.\nAadmi: Ye le kela.\nBhikari: Nahi, mere doctor ne mujhe kela khane se mana kiya hai! 🍌🙅‍♂️🤣",
    "Dost: Bhai meri setting karwa de.\nMe: Bhai mere khud ke lale pade hain, main khud 'a-kela' hoon! 🍌🤦‍♂️😂",
    "Kele ne Watermelon se kaha: Tu itna mota kyun hai?\nWatermelon: Aur tu itna patla aur tedha kyun hai? Gym jaya kar! 🍌🍉💪🤣",
    "Aadmi: Bhai, 1 darjan kela dena.\nDukandar: 50 rupaye.\nAadmi: 40 mein de de.\nDukandar: 40 mein toh chilka milega!\nAadmi: Ye le 10 rupaye, chilka rakh le, baaki kela de de! 🍌💸🤣",
    "Pappu: Aaj kal ladkiyan itna makeup kyun karti hain?\nDost: Jaise kele ko sundar dikhane ke liye uske chilke ki zaroorat hoti hai! 🍌💄😂",
    "Student: Sir, exam mein kuch yaad nahi aa raha.\nTeacher: Toh ek kela kha le, dimag mein potassium aayega!\nStudent: Sir, exam hall mein kela kahan se lau? 🍌📝🤣",
    "Boss: Tumne meeting mein kela kyun khaya?\nEmployee: Sir, aapne hi toh kaha tha 'Go Bananas' with new ideas! 🍌👔😂",
    "Ek aam aur kela bar mein gaye.\nBartender: Kela bhai, aam ko sambhal, wo juice ban chuka hai! 🥭🍌🍸🤣",
    "Santa: Mujhe sapne mein bhagwan dikhe the.\nBanta: Kya bole?\nSanta: Bole roz subah ek kela khaya kar, swasth rahega! 🍌🙏😂",
    "Boyfriend: Baby, main tumhare bina 'a-kela' hoon.\nGirlfriend: Toh bazaar se jaake aur kele kharid lao, guchha ban jayega! 🍌👫🤣",
    "Mummy: Beta sabzi le aana.\nBeta: Aur agar sabzi na ho toh?\nMummy: Toh 2 darjan kela le aana, kela-paneer bana lenge! 🍌🍲🤣",
    "Dost 1: Bhai tu hamesha yellow kapde kyun pehnta hai?\nDost 2: Kyunki main andar se ek dum kele jaisa sweet hoon! 🍌👕😂",
    "Teacher: Kela ko English mein kya kehte hain?\nPappu: Banana!\nTeacher: Aur ek aur kela ho toh?\nPappu: Do-nana! 🍌🍌🤣",
    "Wife: Maine ek face mask banaya hai kele se.\nHusband: Toh lagao, par dhyan rakhna bahar bandar na aa jayein! 🐒🍌💆‍♀️😂",
    "Doctor: Tumhara khoon patla ho gaya hai.\nPatient: Toh kela kha lu, usse gaadha ho jayega? 🍌🩸🤣",
    "Police: Ye kya chura ke bhag raha hai?\nChor: Kuch nahi sir, bas 1 kela tha, wo bhi main kha gaya!\nPolice: Toh chilka kidhar hai?\nChor: Wo main raste mein fenk aya taaki aap fisal jao! 🍌🚔🤣",
    "Kele ka sabse bada dushman kaun?\nWo insaan jo use kharidta hai par khata nahi, aur kela fridge mein kala ho jata hai! 🍌🖤😂",
    "Santa: Maine aaj ek macchar ko kele pe baithe dekha.\nBanta: Phir?\nSanta: Main samajh gaya, machhar bhi ab gym jaane lage hain! 🍌🦟💪🤣",
    "Judge: Tumne padosi ko kyun peeta?\nAaropi: Sir isne meri chat pe kele ka chilka fenka tha.\nJudge: Toh?\nAaropi: Main fisla nahi, isiliye gusse mein isko peet diya! 🍌⚖️😂",
    "Pappu: Bhai, kya kela khane se insaan lamba hota hai?\nChintu: Agar aisa hota toh jungle ke saare bandar Amitabh Bachchan hote! 🐒🍌📏🤣",
    "Wife: Shopping karni hai, kitne paise loge?\nHusband: Main 'akela' jaunga, tum jaogi toh mera diwala nikal jayega! 🍌🛍️😂",
    "Dost: Bhai party ka kya plan hai?\nMe: Aaj raat ko kela shake piyenge aur so jayenge! 🍌🥛😴😂",
    "Teacher: Zameen pe gira kela kya sikhata hai?\nStudent: Ki dhyan se nahi chaloge toh mooh ke bal giroge! 🍌🚶‍♂️🤕🤣",
    "Doctor: Ye tablet kha lena, kiske saath loge?\nPatient: Ek kele ke saath, akele khane mein tablet ghabra jayegi! 🍌💊😂",
    "Santa: Main kela nahi khaunga.\nBanta: Kyun bhai?\nSanta: Iska cover bada ajeeb hai, chain (zipper) hi nahi hai kholne ke liye! 🍌🤐🤣",
    "Aadmi 1: Aaj main akele movie dekhne gaya.\nAadmi 2: Phir kya hua?\nAadmi 1: Pura theatre khali tha, aesa laga jaise kela bina guchhe ke ho! 🍌🎬😂",
    "Wife: Suno, main kela leke aa rahi hoon bazaar se.\nHusband: Thik hai, jaldi aana, varna main 'a-kela' paka jaunga ghar pe! 🍌🏠🤣",
    "Dost: Kela aur dosti mein kya common hai?\nMe: Dono bachpan mein meetha lagte hain aur bade hone pe pak jate hain! 🍌🤝😂",
    "Boss: Humari company ka revenue gir raha hai.\nEmployee: Sir, office ke bahar ek kela rakh do.\nBoss: Usse kya hoga?\nEmployee: Revenue fisal ke seedha upar chala jayega! 🍌📈🤣"
    ]

