# poems.py

BANANA_POEMS = [
    "Peela peela pyara kela,\nSab phalon mein yeh albela.\nChhilka utaro, gup-chup khao,\nSwad iska sabko batao! 🍌🎶",
    "Bandar mama ko bhaya kela,\nDekhte hi lagaya mela.\nEk khaya, dusra khaya,\nFir pet pakad kar zor se chillaya! 🐒🍌",
    "Aam ka raja bhale hi naam ho,\nPar kele bina sab nakaam ho.\nSubah khao ya khao sham,\nKela hi karta hai saara kaam! 🍌❤️",
    "Kela khana aasaan bada,\nNa dhona na kaatna pada.\nChhilka utaro aur chupchap khao,\nApni saari thakan mitao! 🍌😎",
    "Chhilka iska mat girana,\nVarna padega tumhe pachtana.\nPaer padega fisal jaoge,\nHaddi tootegi tab rote aaoge! 🍌🏥",
    "Gym mein jaa kar uthaya bhaar,\nKela khaya maine baar baar.\nBody meri ban gayi bhai,\nKele ne hi yeh shaan badhai! 💪🍌",
    "Gusse mein jab GF aayi,\nMaine turant kela khilaai.\nGussa uska ho gaya chhoo,\nKela ban gaya taranhar bro! 🍌💖",
    "Saste mein ye mil jata hai,\nSabke mann ko bhata hai.\nGarib amir sab khate hain,\nKele ke hi gun gaate hain! 🍌🎶",
    "Fridge mein isko mat rakhna,\nKaala padega bura lagega chakhna.\nBahar rakho aur masti se khao,\nKele ka tum jashn manao! 🍌🎉",
    "Subah subah jab bhookh sataaye,\nChimpu daud ke kela khaaye.\nPet mein ja kar dhoom machaaye,\nChehre par muskaan le aaye! 🐒🍌",
    "Kela hai mera sabse pyara,\nIsne diya mujhe bada sahara.\nBina daant ke ise chabao,\nMasti se tum isko khao! 🍌🥰",
    "Bandar ki hai ek hi maang,\nKele de do mat karo tang.\nAgar nahi doge tum kela,\nMach jayega yahan bada jhamela! 🐒🍌🔥",
    "Seb santra sab hain bekaar,\nKele se hi hai mera saccha pyaar.\nGol gol nahi ye lamba lamba,\nKhakar ban jao tum khamba! 🍌🤣",
    "Duniya gol hai kisne bola,\nDuniya toh hai kele ka jhila.\nThodi tedhi par badi meethi,\nKele jaisi hai ye niti! 🍌🌍",
    "Kela khakar main so gaya,\nSapno mein bhi kela kho gaya.\nSapne mein aaya ek bada kela,\nBola chal ab laga le mela! 🍌😴",
    "Doctor ne jab mujhko toka,\nBola kela khana bada dhoka.\nMaine doctor ko kela khilaya,\nWo bhi kele ka deewana ban gaya! 🍌👨‍⚕️",
    "Zindagi meri akele thi,\nKismat meri paheli thi.\nPhir ek din mujhe kela mila,\nKhushiyon ka jaise phool khila! 🍌🌸",
    "Chhilka utarna ek kala hai,\nKela toh sabka bhala hai.\nAdha chhilka latka ke khao,\nStyle apna tum sabko dikhao! 🍌✨",
    "Kela milk ka banta shake,\nIske aage fail hai cake.\nEk glass jab andar jaaye,\nBacha bacha thumke lagaye! 🍌🥤",
    "Ek din maine kela churaya,\nPiche piche maalik aaya.\nMaine jaldi se chhilka feka,\nMaalik gira aur maine dekha! 🍌🏃‍♂️",
    "Paanch rupaye mein ek kela,\nDekho iska kaisa khela.\nSasta sundar aur tikau,\nIsko khakar ban jao bhau! 🍌💰",
    "Kele ki hai baat nirali,\nIsne meri duniya badali.\nRoz khao tum kela bhai,\nKabhi na leni padegi dawai! 🍌💊",
    "Shaadi mein jab aaya kela,\nDulhan ne bhi chhod diya mela.\nBoli rasgulla nahi khana,\nMujhe toh bas kela hai chabana! 🍌👰",
    "Exam mein jab dimaag na chala,\nMaine chupke se khaya kela.\nAchanak se yaad aaya sab,\nTeacher bhi boli ye kaisa kartab! 🍌📚",
    "Kela jab gusse mein aaya,\nApni jacket ko jaldi utarvaya.\nBola ab main nahi rukunga,\nSidha pet mein hi ghusunga! 🍌😡",
    "Mummy boli beta fruit kha le,\nKele ke tu maje utha le.\nMaine khaye pure darjan,\nMummy ne kiya phir mera visarjan! 🍌🧹",
    "Kele ke upar kaale daag,\nDekh kar mujhko lagti aag.\nPar khane mein hota hai meetha,\nJaise gaon ka koi geetha! 🍌🔥",
    "Aasman mein jaise chamke tara,\nDharti par chamke kela pyara.\nIski chamak se duniya roshan,\nKela khana hai sabse bada tution! 🍌🌟",
    "Kela kela sab chillaaye,\nPar koi isko samajh na paaye.\nAndar se ye bada naram hai,\nChhilka iska uska dharam hai! 🍌🙏",
    "Chimpu aur kela bhai bhai,\nInki jodi hai badi safai.\nEk khata hai dusra khilata,\nYe rishta hamesha muskurata! 🐒🍌🤝",
    "Rat ke baarah baje thi bhookh,\nPet raha tha sookh sookh.\nFridge se maine kela nikala,\nKhate hi ban gaya main matwala! 🍌🕛",
    "Kela khane ki ninja technique,\nSikhlo mujhse bano mat weak.\nEk hath se pakdo chhilka,\nDusre se khao ban ke halka! 🍌🥷",
    "Kele ke bina main kuch bhi nahi,\nYe aadat meri buri toh nahi.\nLog kehte hain bandar mujhe,\nKela chhodne mein kaisa mazza tujhe? 🐒🍌",
    "Tension jab dimaag ko khati,\nKela meri jaan bachati.\nEk bite mein stress out,\nKela khakar I just shout! 🍌🔊",
    "Mobile phone aur ek kela,\nBaaki sab lagta hai jhamela.\nInsta scroll aur kela bite,\nZindagi chal rahi hai ekdum bright! 🍌📱",
    "Pyar vyaar sab dhoka hai,\nKela khane ka accha mauka hai.\nDil tootega toh royega,\nKela khayega toh aaram se soyega! 🍌💔",
    "Ek din maine laya hara kela,\nSocha kaisa hoga ye khela.\nKachha kela muh mein gaya,\nSwad uska bilkul na bhaya! 🍌🤢",
    "Hara kela pakode ke kaam,\nPila kela toh mera salaam.\nKaala kela ban jata cake,\nKela hamesha karta hai make! 🍌🧁",
    "Party mein sab naach rahe the,\nKela hath mein jhaach rahe the.\nJo gira chhilka dance floor par,\nSab gire jaise machi ho tod-phor! 🍌🕺",
    "Kela mera sachcha dost,\nIsko karta hu main sabse zyada toast.\nZindagi bhar sath nibhayega,\nKela mujhko jannat dikhayega! 🍌🥂"
    "Pakadne mein thoda sakht lagta hai shuru mein,\nChilka utre toh mithaas ghulti hai guftgu mein.\nZindagi ke is kele ko waqt de kar toh dekh,\nHar tedhe safar ka asar hota hai rooh mein. 🍌✨",
    "Kaccha tha toh sabne kaha kisi kaam ka nahi,\nRang badla toh mol badh gaya is aam sa nahi.\nWaqt aane par har kela hota hai khaas,\nBas khud par rakhna tu hamesha vishwas! 😉🌱",
    "Lamba hai safar aur tedhi hai rahein,\nKiske aage bhala hum apni baahein failayein?\nKele jaisi fitrat rakh, andar se reh tu naram,\nDuniya chahe jo kahe, tu karta ja apne karam. 🍌💪",
    "Guchhe mein rehne ka alag hi hai maza,\nAkele pan mein toh milti hai bas saza.\nPariksha ki is ghadi mein chilka mat utaar,\nEk kela hi sikhata hai parivaar ka pyaar. 🍌👨‍👩‍👦",
    "Hath mein aate hi log sochte hain kya hoga,\nKhaane ke baad sochte hain asar naya hoga.\nMehnat ka ye kela jo khayega rozana,\nUsi ka ban jayega ek din ye zamana. 😄✨",
    "Upar se peela, thoda tedha dikhta hai,\nPar bajar mein ye apne dum par bikta hai.\nAndar ki mithaas ko chilke mein chupa ke rakh,\nAsli kela wahi jo waqt pe mehakta hai! 🍌😉",
    "Jab chilka utarta hai, tab asli roop aata hai,\nShuru mein har koi thoda sa sharmata hai.\nZindagi bhi kele jaisi hai mere dost,\nJo parda hataye, wahi aage badh jata hai. ✨🍌",
    "Bada ho ya chhota, farq nahi padta,\nJo andar se pakka ho, wo kabhi nahi darta.\nKele se seekh le tu jeene ka saleeqa,\nSabar karne wala hi yahan hai sawarta. 🌱😄",
    "Dabane se pichak jaye, itna naram mat banna,\nBahar se khud ko thoda sakht hi tu rakhna.\nJab koi pyaar se utaare tere guroor ka chilka,\nTabhi apne andar ki mithaas ko tu chakhna. 🍌❤️",
    "Tedhe-medhe rasto par safar hai lamba,\nKabhi akele mat rehna, ban ke tu khamba.\nKele ke guchhe sa tu sabko saath rakh,\nZindagi ka har lamha banega ek achamba. 🍌🤝",
    "Fisal gaye chilke par toh log bohot hasenge,\nTu girega toh taane bhi tujhpe kasenge.\nPar uth kar tu us chilke ko kude mein daal,\nSafalta ke baug mein tere hi kele fasenge! 😂🌱",
    "Daag lag gaye toh kya, aur meetha hota hai,\nBura waqt aane par kyun tu itna rota hai?\nChitkabra kela hi toh asal maza deta hai,\nTapan mein hi toh sona aur khara hota hai. 🍌🔥",
    "Nange badan jab samne aata hai wo,\nApni saari mithaas lutata hai wo.\nKele ki is kurbani ko tu galat na samajh,\nTere svasthya ka poora dhyan rakhta hai wo! 😉💪",
    "Sasta samajh kar log isko chhod dete hain,\nMehenge falon se apna naata jod lete hain.\nPar garib ka sahara yehi kela ban jata hai,\nBhookh lagne par sab isi ko tod lete hain. 🍌🙏",
    "Haath lagate hi kuch log muh banate hain,\nIski tedhi shakal pe tarah tarah ke sawal uthate hain.\nPar jab chakhte hain iski mehnat ka swaad,\nToh ungliyan chaat chaat kar wahi log khate hain. 😄🍌",
    "Hara tha toh kisine mud kar nahi dekha,\nKismat ki lakeeron ka yehi hai ek lekha.\nJab peela hua toh sabhi ne haath badhaya,\nSabar ka kela hota hai sabse meetha. 🍌✨",
    "Dheere dheere pakta hai, jaldbaazi nahi karta,\nKela apni fitrat se kabhi nahi mukarta.\nTu bhi apne waqt ka intezaar kar ae dost,\nSahi samay par hi toh har koi hai nikharta. 🌱⏳",
    "Kacche ko pakaane ki koshish mat kar,\nMasale daal kar usko tu itna mat darr.\nKudrat ke sanchay mein jo kela pakta hai,\nUska swaad hota hai bilkul hi asar. 🍌🌿",
    "Raaton raat koi bada kela nahi banta,\nBina mehnat ke koi aage nahi badhta.\nDhoop aur baarish dono jhelne padte hain,\nTab ja kar market mein hai iska daam chadhta. 🌤️🍌",
    "Thoda naram pad jaye toh fek dete hain log,\nDuniya ko lag gaya hai ye kaisa ajeeb rog.\nOverripe kela hi banata hai sabse achhi bread,\nZindagi ke har phase ka tu kar upyog! 🍞🍌😉",
    "Chhote kele ko dekh kar mat kar andekha,\nUske andar chupa hai mithaas ka bada theka.\nSize par mat ja mere yaar tu yahan,\nChhote packet mein hi bada dhamaka hai dekha. 🍌💥",
    "Subah subah kha lo toh din ban jata hai,\nPet mein ja kar ye bohot sukoon lata hai.\nUrja ka aisa srot aur kahin nahi milega,\nZindagi ki race mein kela hi jitata hai. 🏃‍♂️🍌",
    "Workout ke baad log isko dhoondte hain,\nApni thakan mitane ko isko ghoorte hain.\nTu bhi ban aisi taqat ka zariya sabke liye,\nTere bina sab apne aap ko adhoora samjhte hain. 💪🍌",
    "Na beej ka jhanjhat, na katne ka shor,\nKela khane walo ka hai apna hi ek taur.\nSimple aur saral jivan jeena seekh le isse,\nDikhawe ki is duniya mein tu apni chala daud. 🏃‍♂️✨",
    "Har season mein milta hai, nakhre nahi karta,\nKela kisi ameer ya garib se nahi darta.\nTu bhi apni aukaat zameen se judi rakh,\nAisa insaan hi har dil mein hai utarta. ❤️🍌",
    "Parde ke peeche jo isko chupata hai,\nAsal maza toh wahi akele uthata hai.\nNutrition ki baat kar raha hoon mere dost,\nTu kyun isko galat disha mein le jata hai? 😂🍌",
    "Lamba safar tai karke bazaar mein aata hai,\nDusro ka pet bharne ko khud mit jata hai.\nPrapkar ki is bhavna ko tu pehchan,\nKela hamein sacha tyag sikhata hai. 🙏🍌",
    "Dusro ke chilko par hasna bohot aasan hai,\nPar khud jab girte hain, toh girti shaan hai.\nKele se seekho ek dusre ka sahara banna,\nIsi mein basi insaniyat ki jaan hai. 🤝🍌",
    "Gol nahi, chakor nahi, iska roop thoda hatke hai,\nPhir bhi sabke dilo mein ye zor se jhatke hai.\nUnique hone mein koi burai nahi hai yaar,\nJo alag dikhta hai, wahi toh chamakte hai. ✨🍌",
    "Chhupa ke rakhoge toh sad jayega andar hi,\nBant doge toh banega tu ek bada samandar hi.\nKele ka gyan kehta hai khushiyan tu baant,\nTabhi bajegi teri jeet ki mandar hi. 🎶🍌",
    "Shake bana kar piyo ya khao tu kachha,\nHar roop mein lagta hai kela bada achha.\nZindagi ki har situation mein dhalna seekh,\nTabhi kehlayega tu samajhdaar aur sachha. 🥛🍌",
    "Bahar se chikna, par andar se guddedaar,\nYehi toh hai kele ka sachha kirdaar.\nBahari sundarta par mat ja tu kabhi,\nAndar ki seerat hi karti hai beda paar. 💖🍌",
    "Do din na khao toh kaala pad jata hai,\nJaise bina pyaar ke insaan murjhata hai.\nApno ko waqt dena kabhi mat bhoolna,\nWarna har rista aise hi sad jata hai. 🥀🍌",
    "Bandar bhi janta hai iski asli keemat,\nInsaan hokar tu kyun dikhata hai aisi neeyat?\nJo cheez asani se milti hai, uski qadar kar,\nKele mein chupi hai sehat ki waseeyat. 🐒🍌",
    "Sone ke rang sa chamakta hai bazaar mein,\nKoi isko khata hai akele, koi khata hai parivaar mein.\nKhushiyon ka yeh roop har jagah dhal jata hai,\nKele ka swaad hai sabse bada is sansaar mein. ✨🍌",
    "Aandhi aur toofan mein ped tedha hota hai,\nUsi se toh kele ka aakar bhi badalta hai.\nHalaat chahe jitne bhi kathin kyun na ho,\nMushkilo se hi insaan ka roop nikharta hai. 🌪️🍌",
    "Todne walo ne badi berukhi se toda hai,\nPar kele ne apno ka saath kahan chhoda hai.\nGuchhe mein reh kar usne shakti dikhayi,\nEkta ne hi har toofan ka muh moda hai. 🤝🍌",
    "Bageeche ki shaan hai iske bade bade patte,\nPar fal dene mein ped laga deta hai apne satte.\nDusro ki khushi ke liye khud ko mita dena,\nKele ke ped ne ye sikhaye hain raste achhe. 🌿🍌",
    "Na aawaz karta hai, na karta hai shikaayat,\nSahi waqt par kela karta hai sabki hifaazat.\nBhookhe ko khana aur bimar ko taqat,\nKhamoshi se apna farz nibhana hai iski aadat. 🤫🍌",
    "Pake hue kele ko bacche bhi khate hain,\nDaant na ho jinke, wo bhi swaad udate hain.\nApni bhasha aur vyavahar itna naram rakh,\nKi har umar ke log tere paas chale aate hain. 👶👴🍌",
    "Sardi ho ya garmi, kela humesha sath hai,\nYe sasti si cheez mein kya gajab ki baat hai.\nApne dosto ke liye tu bhi aisa hi ban,\nJo har mausam mein thaame unke haath hai. 🤝🍌",
    "Chilka utarne ka tarika sabka apna hota hai,\nKoi upar se chhilta, koi tod ke khata hai.\nZindagi jeene ka bhi apna hi andaaz rakh,\nJo tujhe sahi lage, wahi sabse accha hota hai. 😉🍌",
    "Thoda lamba safar hai, thodi mushkilein hain aam,\nPar kele jaisa banega toh hoga tera bhi naam.\nAndar se meetha reh aur bahar se strong,\nTabhi milega tujhe safalta ka inaam. 🏆🍌",
    "Ek din me nahi pakta sapno ka kela,\nLagta hai saalo saal ka lamba mela.\nSabar ka swaad jisne chakh liya yahan,\nWahi jeet-ta hai duniya ka yeh jhamela. ⏳🍌",
    "Kela jab guchhe se alag hota hai,\nThodi der mein hi wo sadne lagta hai.\nApno se dur ja kar koi khush nahi rehta,\nParivaar ke saath hi insaan waqt me badhta hai. 👨‍👩‍👦🍌",
    "Nange hatho se usko daba kar mat dekh,\nHar kele ka apna ek hota hai vishesh lekh.\nKisi ki kamzori ka mazaak mat uda,\nKhuda ne sabko di hai apni ek alag hi rekh. ✋🍌",
    "Peela rang dekh kar log lalchate hain,\nMithaas ki umeed mein usko ghoorte jate hain.\nApne andar bhi aise gun paida kar tu,\nKi log teri sangat mein aane ko taras jate hain. ✨🍌",
    "Jo ped sabse jhuka hota hai, usme utne aam nahi hote,\nKele ke ped humesha seedhe kahan hote?\nBojh falon ka usko bhi jukha deta hai,\nPar mehanat ke fal sabko aaram kahan dete. 🌳🍌",
    "Chilka nikalne ke baad wajan kam ho jata hai,\nJaise ghamand chhodne par insaan halka ho jata hai.\nEgo ka yeh chilka utaar kar toh dekh,\nTera asli swaroop sabko lubhata hai. 😌🍌",
    "Kacche kele ki sabji badi swadisht banti hai,\nPakne ki raah dekhne ki nahi zarurat hoti hai.\nZindagi ke har stage mein apna talent dikha,\nHar umar mein insaan ki ek alag keemat hoti hai. 🍳🍌",
    "Jab tak na khule, lagta hai kitna raaz chupa hai,\nAndar jaise koi meetha sa taaj chupa hai.\nZindagi ke band darwaze khol kar toh dekh,\nHar mushkil ke piche ek naya saaz chupa hai. 🔑🍌",
    "Do kele jod kar bhi ek nahi bante,\nHar ek ki pehchan uske apne sapne bunte.\nDusro ki nakal karke kahan tak jayega,\nOriginality hi toh duniya wale hain sunte. 🌟🍌",
    "Kela fisalne ka kaam bhi karta hai,\nPar dhyaan se chalo toh aage bhi badhata hai.\nGalatiyan tumhe girane ke liye nahi hoti,\nUnse seekh kar hi insaan manzil pata hai. 🚶‍♂️🍌",
    "Sasta hai isliye sabko mil jata hai,\nMehenge falon ko ye peeche chhod aata hai.\nSaadgi mein hi sabse badi taqat hoti hai,\nYehi ek sabak hume kela sikhata hai. 🧘‍♂️🍌",
    "Iski mehak door se hi pehchaan aati hai,\nAndar ki achhai khud ba khud dikh jaati hai.\nApne karm aise rakh ki log tujhe dhoonde,\nSachi shohrat aise hi zindagi mein aati hai. 🌺🍌",
    "Khada karne mein usko waqt lagta hai ped par,\nPar girne mein usko bas lagti hai ek hi pal.\nIzzat aur kele dono mehanat se ughte hain,\nBacha kar rakh inko tu, mat kar apne ko kal. ⏳🍌",
    "Tedha zaroor hai par irade iske nek hain,\nNutrition se bhare iske saare ke saare ansh hain.\nInsaan ki surat se uski seerat na naap,\nTedhe logo mein bhi chupe hote kitne bhesh hain. 🎭🍌",
    "Daba ke dekha toh andar se bilkul guddedaar tha,\nUpar se lagta jaise kitna nakhredar tha.\nBaar se gusse wale log andar se naram hote hain,\nUnka dil samajhna hi sacha karobaar tha. ❤️🍌",
    "Chilka pakad kar usko zor se tu mat kheenchna,\nPyaar se kholna usko, mat aakhon ko meenchna.\nZindagi ke rishto mein bhi narmi ki zaroorat hai,\nGusse se apni baaton ko tu kabhi mat seenchna. 🤝🍌",
    "Pura khol doge toh tutne ka darr hai,\nAdha khol kar khana, yehi sahi safar hai.\nApne saare raaz ek baari mein mat khol,\nRahasya banaye rakhna, chaturai ka asar hai. 🤫🍌",
    "Ek dum se muh me pura mat daal lena,\nChba chaba kar swaad usko apne andar lena.\nZindagi ki khushiyan dheere dheere jeeni chahiye,\nJaldbaazi mein sab kuch kahin tu mat kho dena. 🍽️🍌😉",
    "Kela kehta hai mujhe bas tu ek hi baar kha,\nBaar baar wahi galti karke tu kahan jayega?\nExperience se seekh lena hi samajhdaari hai,\nWarna phir se chilke par tu fisal hi jayega. 😂🍌",
    "Kala ho gaya thoda, toh logo ne thukra diya,\nWaqt ke sitam ne usko kachre mein bitha diya.\nPar us kale kele ka cake bada zabardast banta hai,\nTute hue insaan ne phir naya itihas racha diya! 🎂🍌",
    "Chipka rehta hai guchhe mein apni maa se,\nAlag hote hi darta hai wo us hawa se.\nApne roots se jude rehna aasan nahi hai,\nPar akele astitva tut jata hai kisi wajah se. 🌳🍌",
    "Kele ki tarah tu bhi apna curve maintain kar,\nSidhe raston par chalne ka ab chhode ye safar.\nZindagi mein flexibility hona bohot zaroori hai,\nThoda mod aane par mat ghabra mere humsafar. 🛤️🍌",
    "Uske aage kuch aur lajawab nahi lagta,\nBhookh lagi ho toh kela hi hisaab lagta.\nMusibat ke waqt jo dost tera kaam aaye,\nWahi asal mein zindagi ka aaftab lagta. ☀️🍌",
    "Saath mein iske doodh ho toh aur maza aata hai,\nDono ka milan ek behtareen shake banata hai.\nZindagi mein bhi ek ache sathi ki talash kar,\nJo tere guno ko aur bhi ubhaar jata hai. 🥛🍌✨",
    "Sardi mein khao toh gala kharab kar deta hai,\nGalat waqt pe uthaya kadam sab barbaad kar deta hai.\nKele se seekh ki timing ka bada asar hota hai,\nSahi samay par kiya kaam hi aabaad kar deta hai. ⏱️🍌",
    "Chhote kele ki mithaas bade se zyada hoti hai,\nYe baat kitne logo ko samjh aati hai?\nZindagi mein chhoti chhoti khushiyan hi asli hain,\nBadi chizo ke piche bhaag ke bus umar ghatti hai. 🐣🍌",
    "Lamba lamba aur peela peela, dekh sab lalchate,\nPar bina paka hua chilka khol nahi wo paate.\nMehnat karne ka waqt aaye toh sab peeche hatte,\nSirf meetha swaad chakne ke liye sab aage aate! 😄🍌",
    "Ek dusre ke upar guchhe mein laday rehte hain,\nPar musibat aane par ek sath khade rehte hain.\nParivaar ki ladai bhi bilkul iske jaisi hoti hai,\nDil me ek dusre ke liye hamesha pyar rakhte hain. ❤️🍌",
    "Niche se kata hua ho toh swaad badal jata hai,\nZindagi ka rasta galat mude toh rukh badal jata hai.\nHar kadam soch samajh kar rakhna mere yaar,\nEk galti se kela nahi, naseeb sad jata hai. 👣🍌",
    "Roz kela khane se takat bohot milti hai,\nAndar ki urja jaise naye sire se khilti hai.\nRoz kuch naya seekhne ki aadat daal le tu,\nIsi se tere aane wale kal ki kismat khilti hai. 🌟🍌",
    "Sasti cheez dekh kar muh mat fer lena,\nGun dekhna, usko aaram se gher lena.\nKele ki tarah jo simple dikhta hai asar me,\nWahi samay aane par laga deta hai sabki naiyya kinare me. 🚣🍌",
    "Iske aakar pe log bohot phabtiya kaste hain,\nJo samajh nahi paate wahi ispe hasste hain.\nTeri kamyabi pe bhi log aise hi taane denge,\nUnki parwah na kar, ashiq bas apni dhun me baste hain. 🎶🍌",
    "Gila chilka farsh par pada ho toh bacha ke nikal,\nKisi doosre ki galti ka faida uthane se pehle sambhal.\nKarma ka chakra ghume toh tu bhi fisal sakta hai,\nIsliye hamesha auro ke raste ka kanta tu nikal. 🚶‍♂️🍌",
    "Kaccha hara rang dekh kar dil na gabraye,\nBada lamba kela bhi dheere dheere pak jaaye.\nZindagi ke har stage ko enjoy karna seekh le,\nHar mausam apne sang ek naya tajurba laaye. 🌦️🍌",
    "Haath me lene se pehle log isko bapuhte hain,\nIski mehak aur narmi ka bada dhyaan rakhte hain.\nHar insaan ko aise hi izzat se tu treat kar,\nSabke andar ek komal sa dil humesha dhadakte hain. 💓🍌",
    "Sone ki thaali me rakh ya rakh zameen par,\nKele ka swaad kabhi nahi badalta umeed par.\nApni asal fitrat tu bhi hamesha wahi rakhna,\nChahe mil jaye taaj ya fir baithe tu ameer par. 👑🍌",
    "Tedhe ko seedha karne ki koshish tu bekaar kare,\nUski asal khoobsurati toh iske gumaav me chhipe.\nZindagi ki tedhi raaho se pyaar kar le tu ab,\nManzil se sundar toh rasto ke hi rang hain dikhe. 🌈🍌",
    "Bandar ko kela do toh wo usko kholta pichhe se,\nHum log kholte hain usko uske tute hue guchhe se.\nHar kaam ko karne ka tarika naya ho sakta hai,\nEk dusre ki techniques se seekh lo thode rutbe se. 🐒🍌",
    "Chilka utarte waqt dhyaan rakh uske reshon ka,\nWoh dhage jaise lagte hain, hissa hain uske bheshon ka.\nChhoti baato ko zindagi me kabhi nazarandaaz na kar,\nYehi hissa hote hain hamare saare vishesho ka. 🧵🍌",
    "Thoda purana ho gaya toh uspe nishaan pad jate,\nLekin un dagon me bhi tajurbe hain nazar aate.\nBudhape se kabhi darna mat tu ae mere dost,\nWo daag tumhe aur bhi meetha aur pyara hain banate. 👴🍌",
    "Iski pooja bhi hoti hai aur isko khaya bhi jata,\nHar roop me kela kitna upyogi hai kehlata.\nApne andar aisi sharam aur shakti paida kar,\nKi har koi tera sahyog apne paas hai pata. 🙏🍌",
    "Peene me bhi kaam aaye, aur khane me bhi hit,\nKele sa ban ja, har situation me ho ja tu fit.\nAdaptability jisko kehte hain angrezi me,\nWo aadat la laye zindagi me ban ke tu super hit! 🌟🍌",
    "Ek baar kela fisla toh chilke ki bhi galti,\nDusri baar gira toh hai teri khud ki marzi.\nZindagi tujhe do mauke hamesha deti hai,\nSeekh le warna sab samjhenge tujhe farzi! 😂🍌",
    "Bazaar me guchho me kela laktka rehta,\nDusro ka ghar basane ko apna aakar jhelta.\nKhud ko kurban karna iski fitrat hai yaaro,\nEk acha insaan bhi kisi ka bura nahi sehta. 🏘️🍌",
    "Kela agar aakar se chota ho toh usme sharam nahi,\nJo swaad de na sake uspe hota mujhe bharam yahi.\nKaam aisa kar ki tera asar sabse bada ho,\nBadi baatein phekne se kisi ka uddhar garam nahi. 🔥🍌",
    "Upar ka hissa jara sakht lagta hai kaatne me,\nPar andar ka roop maza deta hai poora baantne me.\nApne dil ka rasta shuru me sakht hi tu rakh,\nTakleef kam hogi sache dosto ko chhatne me. 🛡️🍌",
    "Pakadne ke liye isko, tu theek se banana grip,\nKela agar geela ho toh hath se kar jayega slip.\nMauke bhi zindagi me aise hi nikal jate hain,\nSavdhani hatti toh life dedegi tujhe ek badi dip. 🎢🍌😉",
    "Kholne ke chakkar me log naakhun chala dete,\nKele ka wo komal hissa jaldi daba dete.\nZindagi ke komal risto ko itni jor se na pakad,\nThodi si chot aane pe log unhe bhula dete. 💅🍌",
    "Garm hawa me jaldi se iska roop kaala hota,\nWaise hi bure dosto me insaan kharab hala hota.\nApni sangat humesha soch samajh kar tu chun,\nAccho ke saath hi har faisla bada niraala hota. ☀️🍌",
    "Sasta hai, par energy deta kamaal ki botal,\nDiet ho ya workout, iski zarurat padti total.\nApne skill set ko tu itna versatile bana,\nKi tere bina kisi ka kaam na ho sake local. 🏋️‍♂️🍌",
    "Kela khao aur chilka feko mat idhar udhar,\nAage badh kar jimmedari uthane ka ban ja nidar.\nChhoti si galti bhi rasta tera bhatka sakti hai,\nIsliye har kadam par rakh khud ki tu poori khabar. 👁️🍌",
    "Thoda sa mudna zaroori hai aage badhne ko,\nKela seedha kahan hota ped pe chadhne ko.\nZid mat pakadna kisi baat ko leke itni,\nJhukna padta hai uchaiyo ko apne padhne ko. 📈🍌",
    "Jo dikhta hai wahi andar bhi bhara rehta,\nKela kabhi bahari roop pe nakab nahi pehnta.\nZindagi me tu bhi bilkul transparent reh,\nSacha aadmi kisi saanche me aakar nahi dhalta. 💧🍌",
    "Doosre kele par apni chhaya de kar bachata,\nGuchhe ka ped hume parivaar ki maya dikhata.\nAkela chhod do kisi ko toh dhoop se sad jayega,\nSaath reh kar hi wajood nikhra nikhra sa aata. 🌞🍌",
    "Bina beej ke bhi apna parcham lehrata hai,\nKela har mausam me sabko yaad bohot aata hai.\nTeri shuruat chahe kitni bhi adhuri kyu na ho,\nMehnat ka swaad tere kal ko poorn banata hai. ✨🍌",
    "Kaccha aur sakht, sab usko todna chahte,\nThoda naram padne par sab usko chodna chahte.\nInsaan ki fitrat ka ye kaisa ajeeb khel hai,\nKele ko dekh sab apna muh waise modna chahte. 🤔🍌",
    "Patte se leke chilke tak, sabka apna daam hai,\nKele ke har ansh ka duniya me apna ek naam hai.\nTeri kamzori bhi kal teri taqat ban jayegi,\nKhud ko dhoondna hi zindagi ka asal aayam hai. 🗺️🍌",
    "Jo iska ras pi le, uski aatma trupt hoti hai,\nJiske paas ye na ho, uski saansein ruki hoti hain.\nPait ki bhookh ke aage har koi majboor hai,\nKele ki roti logo ke kitne dukh dhoti hai. 🍞🍌",
    "Kuch logo ka dhyan bas iske size par ruka hai,\nPar asal maza toh iske swaad ke roop me jhuka hai.\nInsaan ko uske kapdo ya rutbe se tu mat parakh,\nSachi insaniyat uske dil ke kisi kone me aakar ruka hai. ❤️🍌",
    "Peela aur hara, dono roop hain iske chamakte,\nKacche log rote, par pake hue hain mehakte.\nZindagi tu apne andaz se apni marzi ki jee,\nDekhna ek din tere taare bhi falak pe dhamakte. 🌟🍌",
    "Jisne guchhe se alag hoke chilka apna faad liya,\nSamajh lo usne apni izzat ka ghar ujad diya.\nKhole hue kele ko thodi der khula mat chhod,\nSamay ki dhoop ne na jane kitno ko mar diya. 🥀🍌",
    "Kela pakadne me thoda naram thoda sakht sa,\nKha lo toh swaad lagta bilkul hi alag sa.\nZindagi bhi yahi kela hai mere pyaare dost,\nJiyo toh lage jaise har din naya janat sa! 🍌✨💖"
]

BANANA_QUOTES = [
    "Zindagi ke safar mein kele sa meetha ban,\nChhilke sa ahankaar chhod aur sacha insaan ban! 🍌✨",
    "Waqt ke sath kela pakta hai aur hota hai lajawab,\nSabr rakh mere dost, zaroor poore honge tere khwab! 🍌🌟",
    "Andar se naram aur bahar se sakht apna aavaran rakh,\nKele ki tarah tu bhi is duniya mein apni pehchan rakh! 🍌💪",
    "Kele ka chhilka sikhata hai humein girna aur sambhalna,\nMushkilon ke bawajood bhi seekho aage nikalna! 🍌🚶‍♂️",
    "Duniya tujhe tedha kahe, par tu apni mithaas mat chhod,\nKele ki tarah bina bhedbhav ke har dil se rishta jod! 🍌💛",
    "Saste mein milta hai kela, par takat iski mahan hai,\nSaadgi mein jeene walon mein hi basti asli jaan hai! 🍌🌿",
    "Chhilka utar kar dekho, kela hota bilkul saaf hai,\nSacha dil rakhne walon ke liye har chhoti galti maaf hai! 🍌🕊️",
    "Gusse ka chhilka utar de, aur andar se tu naram ban,\nKele jaisi mithaas la, aur acche apne karam ban! 🍌🧘‍♂️",
    "Akelepan se mat ghabra, kela bhi toh a-kela hai,\nKhud par tu vishwas rakh, yeh duniya ek mela hai! 🍌🎪",
    "Kele ke jaisa ban, jo har haal mein saath nibhata hai,\nChahe bimari ho ya thakan, yeh hamesha takat badhata hai! 🍌🔋",
    "Bahar se chahe daag lag jaye, par andar se safed rehna,\nKele ki tarah har musibat ko tu haste-haste sehna! 🍌😊",
    "Jab tak chhilka na utre, kele ka swaad nahi aata,\nJab tak mehnat na ho, tab tak koi safal nahi ban pata! 🍌🏆",
    "Peele rang ka kela jaise roshan karta hai din,\nWaise hi mehnat ke bina aati nahi safalta tere bin! 🍌☀️",
    "Sasta samajh kar kele ko tu kabhi na bekar maan,\nIs chhote se phal mein chhupi hai badi-badi jaan! 🍌🔥",
    "Kele ko dekho, bina guroor ke ped par latakta hai,\nJo jhukta hai nirmalta se, wahi asmaan ko chhoota hai! 🍌🌳",
    "Jaise kela deta hai fauran nayi urja ka ehsaas,\nWaise hi hamesha zinda rakh apne andar ki aas! 🍌⚡",
    "Tedha hokar bhi kela sabko meetha lagta hai,\nSacchi niyat ho toh har koi accha lagta hai! 🍌💖",
    "Kele jaisa naram dil rakh, kisi ko na tu sata,\nApni acchai se is duniya mein naya itihaas bana! 🍌📖",
    "Kele ko chheelne par milti hai andar ki mithai,\nBina parishram kiye kabhi kisi ne manzil nahi pai! 🍌🏔️",
    "Har din ek kela kha, aur apne lakshya par dhyan laga,\nKathinaiyon se mat darr, bas aage kadam badha! 🍌🚀",
    "Kela nahi dekhta ki tu ameer hai ya gareeb,\nMehnat karne walo ke hi aate hain khushiyan qareeb! 🍌💰",
    "Kele ke ped ka har hissa kaam mein aata hai,\nParopkar se hi manushya mahaan ban jata hai! 🍌🌿",
    "Bahar ka roop kaisa bhi ho, aatma ko tu shuddh rakh,\nKele ki tarah har haal mein apne vicharon ko buddh rakh! 🍌🧠",
    "Jaise kela mita deta hai bhookh pal bhar mein,\nWaise hi tu laa khushiyan sabhi ke ghar mein! 🍌🏡",
    "Kele ki tarah mithaas ban kar sabki zindagi mein ghul ja,\nApne ahankaar ko bhool kar sabke dilon se mil ja! 🍌💞",
    "Kele ka chhilka giraye, par kela takat de jaye,\nZindagi mein jo sikh le is se, wo har mushkil par vijay paye! 🍌🏅",
    "Kele ka ped bina beej ke bhi apna vistar karta hai,\nSachha gyaan wahi hai jo khud ko jagruk karta hai! 🍌🌱",
    "Chahe ho upvaas ya tyohar, kela hamesha paas hai,\nSacche dost ki tarah yeh rishta bada hi khaas hai! 🍌🤝",
    "Bina daant wala bhi kele ko aaram se khata hai,\nSaralta se hi insaan sabke dilon par chha jata hai! 🍌👴",
    "Kele ki khushboo se jaise mehek jata hai aas-paas,\nWaise hi apne karmon se paida kar ek naya vishwas! 🍌🌬️",
    "Kaala padne par bhi kela meetha cake banata hai,\nBure waqt mein bhi accha insaan raasta nikal hi lata hai! 🍌🎂",
    "Kele ki tarah apna mol kabhi na girne de,\nSamay aane par sabko tu apni chamak dikhne de! 🍌✨",
    "Ek kela aur ek muskaan, dono mein hai ajeeb si shakti,\nInke bina adhuri hai is jeewan ki bhakti! 🍌🙏",
    "Kele ka guchha sikhata hai ekta ki pehchan,\nMil kar rehne mein hi chhupi hai sabki shaan! 🍌🤜🤛",
    "Jaise kela jald hi hazam ho kar asar dikhata hai,\nAccha vichaar bhi turant man ko shanti dilata hai! 🍌🕊️",
    "Bina aawaz kiye kela chupchap ped par ugta hai,\nKhamoshi se mehnat karne wala hi asmaan chhoota hai! 🍌🌌",
    "Kela khate hi jaise thakan sari mit jati hai,\nSacchi preet se hi toh dil ko rahat mil jati hai! 🍌❤️",
    "Chhilke ko kachre mein daal, aur kele ka tu le swaad,\nBuri baaton ko bhool kar, rakh acchi yaadein yaad! 🍌🚮",
    "Kela jaise har fal mein apna rang jamata hai,\nVyavahaar kushal insaan sabka pyara ban jata hai! 🍌🎨",
    "Jab tak kela poora na chhile, swaad aadhura rehta hai,\nJab tak dil saaf na ho, pyar poora kahan hota hai! 🍌💯",
    "Kela sikhata hai ki mithaas khud ke andar hoti hai,\nBahar dikhawe mein duniya apni keemat khoti hai! 🍌💎",
    "Kele ki sasti keemat uski shreshthta nahi batati,\nInsaan ki saadgi hi uski mahanata hai dikhati! 🍌🌟",
    "Bina kate, bina jale, kela turant khaa sakte hain,\nSaral vyavahar se hum har dil ko jeet sakte hain! 🍌🎈",
    "Kela jitna purana hota, utna hi mithaas lata hai,\nSaccha anubhav insaan ko aur samajhdar banata hai! 🍌🧠",
    "Ped se toot kar bhi kela apni taazgi banaye rakhta hai,\nApno se door hokar bhi sacha dost rishta nibhaye rakhta hai! 🍌🏡",
    "Kele ki shakal ek khubsurat muskaan jaisi hoti hai,\nMuskurahat hi toh har gam ko mitane ki kadi hoti hai! 🍌😊",
    "Kela apna sab kuch bina kisi swarth ke de jata hai,\nNiswarth bhav se jeene wala hi bhagwan ko pata hai! 🍌🙌",
    "A-kela hokar bhi kela kabhi khud ko akela nahi manta,\nKhud par ho yakin toh insaan kisi ko bada nahi manta! 🍌🦅",
    "Jaise kela deta hai urja har nayi subah ke aane par,\nWaise hi umeed rakho har naye sapne ke sajane par! 🍌🌅",
    "Chimpu ki ye seekh hamesha dil mein basakar rakhna,\nKele jaisa ban kar duniya mein apni pehchan zinda rakhna! 🍌🐒"
        "Zindagi us kele ki tarah hai, jise agar waqt par na khaya jaye, toh woh bilkul kaala aur kharab ho jata hai. Waqt par kela khao, khush raho! 🍌✨",
    "Pyar karna toh kela khane jaisa hai, aage badhna hai toh chhilke (ego) ko utarna hi padega! 😉🍌",
    "Duniya gol nahi hai, duniya kele ke aakar ki hai. Isliye yahan sab thode tedhe hain! 🐒🍌",
    "Sacha dost wahi hai jo apna aakhri kela tumhare sath share kare. 🍌🤝",
    "Har subah ek naya kela hai, use tod kar hi meethas ka swad chakhna hai. 🌅🍌",
    "Kele mein bhi sabak hai: bina chhilke utare, koi bhi apna swad nahi dikhata. 💪🍌",
    "Jeet unki hoti hai jo kele ko bhookh se nahi, samajh se khate hain. 🧠🍌",
    "Sapne wahi poore hote hain jo kele ki tarah dhairya se pakte hain. 🌟🍌",
    "Kela khane se pehle uski chhil utarna seekho, zindagi mein bhi mushkilon ko aise hi pehchano. 🔥🍌",
    "Kacha kela bhi kabhi pak jaata hai, bas waqt ka sahara hona chahiye. ⏳🍌",
    "Jab tak kele mein daag nahi, tab tak woh sachcha meetha nahi. Zindagi bhi daagon se nikhar jaati hai. 🌼🍌",
    "Kele ki tarah jhuk kar chalna seekho, toofan bhi nahi gira sakta. 🌊🍌",
    "Jo apna kela dusron ko khilata hai, uski jholi kabhi khali nahi hoti. 🙏🍌",
    "Kele ka rang dekho: peela ruhaniyat hai, hara umang, kala anubhav. 🎨🍌",
    "Kele ki tond tedhi hoti hai, par andar ka meethas seedha dil jeet leta hai. ❤️🍌",
    "Chhilka fek kar aage badho, zindagi ka asli swad andar chhupa hai. 🚶🍌",
    "Jis din kele ki kadar karna seekhoge, us din amiri tumhare paas aayegi. 💎🍌",
    "Kele mein chhupa raaz: kamjor dikhkar bhi sakht se sakht haalat ko meetha kar dena. 🛡️🍌",
    "Thoda sa kela, thoda sa pyaar – din ban jaaye bahaar. 🌸🍌",
    "Kele ki tarah apni pehchan banao, log tumhara naam na bhoolenge. 🏆🍌",
    "Jab zindagi kela de, to usse kehna – main tujhe aur meetha kar dunga. ✨🍌",
    "Kele ki kasam, jo mehnat karta hai wohi meethas paata hai. 🛠️🍌",
    "Kele ko dekhkar mat haso, isi tedhepan mein seedhi baat hoti hai. 😊🍌",
    "Har kela ek kahani hai, kuch meethe, kuch kachche – par sabhi ke apne rang hain. 📖🍌",
    "Akele mat khao kela, baantne se meethas badhta hai. 🤲🍌",
    "Kele ka chhilka pheekha par andar ka swad anmol. Insaan bhi aisa hi hota hai. 🌟🍌",
    "Jo kele ko aadha todta hai, woh poora sukh nahi samajhta. ☯️🍌",
    "Kele pe likha hai: dhairya rakho, pakne do, apne aap meethas aayega. 🕊️🍌",
    "Kele ki chhilkiyon se naa ghabrao, yeh giraane ke liye nahi, utarne ke liye hoti hain. 🧗🍌",
    "Zindagi ke kade sapno ko kele ki tarah meetha kar do, har mushkil halwa ban jayegi. 🍯🍌",
    "Kele mein utni hi shakti hai jitni ek muskaan mein. Dono hi mithaas baant te hain. 😁🍌",
    "Jisne kela khaya, usne jeena seekha. Jisne baanta, usne jeetna seekha. 🥇🍌",
    "Kele ka haath kabhi akela nahi hota, jhund mein khilta hai. Vahi zindagi ki seedh. 🌿🍌",
    "Kele ki umar kam, par yaad baqi rakh jaata hai. Aisa bano tum bhi. 🕰️🍌",
    "Tedha kela tedha raasta, par manzil meethi hoti hai. 🛤️🍌",
    "Kele ki mithaas chhilkewalon ko nahi, khane walon ko pata chalti hai. 🤫🍌",
    "Kele ki tarah apni jaroorat se zyada mat jhuko, toot jaoge. ⚖️🍌",
    "Kele ka rang utarne se nahi, pakne se aata hai. Insaan bhi waqt se nikhrta hai. 🌈🍌",
    "Sapne wahi sach hote hain jo kele ki tarah haath se tod kar khaye jaate hain. 👐🍌",
    "Jo kela khilane aaye, use kabhi bhukha mat jaane do. 🍽️🍌",
    "Kele ki tarah garam dhoop mein bhi apni mithaas mat khona. ☀️🍌",
    "Kele se seekho: bina shor ke apni meethas failana. 🎶🍌",
    "Kele ki tarah agar koi tumhe chhilke phek de, to samajhna ab asli meethas tumhara hai. 🔥🍌",
    "Jab tak kele mein daane nahi, tab tak woh kacha hai. Insaan bhi sangharsh se damdaar hota hai. 💪🍌",
    "Kele ki jhadi ko paani chahiye, sapno ko mehnat. 🌧️🍌",
    "Kele ko mat dekho ke woh tedha hai, dekho ke woh kitna meetha hai. 😌🍌",
    "Kele ki tarah girna bhi seekho, phir uthkar aur meetha banana. 🚀🍌",
    "Jo kele ko pooja ke prasad chadhaye, uski jholi kabhi khali nahi rehti. 🛕🍌",
    "Kele ki tarah saaf raho, andar se meetha, bahar se chamakta. ✨🍌",
    "Kele ke bina prasad adhoora, kele ke bina zindagi sooni. 🙌🍌",
    "Kele ka chhilka utarna seekho toh har mushkil hal ho jati hai. 🔑🍌",
    "Kele ki tarah apni pehchan banao, ki log tumhe dekhkar muskuraye. 😊🍌",
    "Kele ko koi nahi puchta ki tune kitna meethas chhupaya, woh apne aap meetha lagta hai. 🌟🍌",
    "Kele ki tarah kabhi mat ruko, pakte raho, meetha hote raho. 🌱🍌",
    "Kele ki kasam, jo waqt par pak gaya, wohi ameer bana. ⏰🍌",
    "Kele mein bhi gyan hai: andar se mazboot, bahar se komal. 🧘🍌",
    "Kele ki tarah mushkilon ko chhilkar andar ki takat dikhao. 💥🍌",
    "Kele ki mithaas ka raaz: dhoop aur paani dono saha, phir meetha hua. 🌦️🍌",
    "Kele ki tarah jhuk kar baat karo, par kabhi apni mithaas mat girne do. 🎯🍌",
    "Kele se seekho, thode se mein bhi bada sukh dena. 🎁🍌",
    "Kele ki tarah raaste mein bhi agar koi tod le, to bhi meethas baant do. 🛣️🍌",
    "Kele ki chhilkiyon ko naa gin, andar ka meethas chakh. 🧭🍌",
    "Kele ke liye naa koi jaat, naa koi baat; woh sabko meetha lagta hai. 🌍🍌",
    "Kele ki tarah apne sapno ko dhairya se pakne do, waqt aane par khud meethas milega. 🌄🍌",
    "Kele ki tarah agar koi tumhe chhilke utaare, toh samajhna woh tumhari mithaas dekhna chahta hai. 👀🍌",
    "Kele ki mithaas uske andar hoti hai, waise hi insaan ki khoobi uske andar. 🧠🍌",
    "Kele ki tarah apni mithaas ko kabhi chhupao mat, duniya ko meetha karo. 🌎🍌",
    "Kele ki tarah agar koi tumhe utha kar rakhe, toh khud ko uske kabil banao. 🏺🍌",
    "Kele ki tarah kabhi akela mat raho, jhund mein mithaas badhti hai. 👥🍌",
    "Kele ki tarah meethas baantne se khud kam nahi hota, badhta hai. 📈🍌",
    "Kele ki tarah tedha hona bhi ek kala hai, seedha dil rakho toh sab theek ho jata hai. 💖🍌",
    "Kele ki tarah waqt se pehle mat todo, apne aap pakne do. 🍃🍌",
    "Kele ki tarah agar koi tumhe kaala kahe, toh kehna ki main pakkar meetha ho gaya. 🖤🍌",
    "Kele ki tarah kabhi apni mithaas ko bhoolna mat, wahi tumhari pehchan hai. 🏅🍌",
    "Kele ki tarah duniya ko bata do ki meethas chhilkewalon ke liye nahi, khane walon ke liye hai. 🍬🍌",
    "Kele ki tarah gir kar bhi uttho, aur phir se meetha bano. 🌀🍌",
    "Kele ki tarah apni khushi khud bano, kisi ke haath ki chhilki mat bano. 🦋🍌",
    "Kele ki tarah kabhi apne rang pe naa itrao, meethas to andar ka hai. 🌈🍌",
    "Kele ki tarah hamesha swaadisht raho, chaahe koi kahe tedhe ho. 😜🍌",
    "Kele ki tarah apni umar bhar meethas do, jaate jaate bhi kisi ke kaam aao. 🕯️🍌",
    "Kele ki tarah mushkilon ko chhilkar andar ki meethas ko bahar lao. 🗝️🍌",
    "Kele ki tarah kuch log tedhe hote hain par unka dil meetha hota hai. 💗🍌",
    "Kele ki tarah sabko apni mithaas ka ehsaas karwao, par khud pe naa garv karo. 🙇🍌",
    "Kele ki tarah kabhi haarna mat, hamesha pakte raho. 🔄🍌",
    "Kele ki tarah agar koi tumhe tod de, toh use mithaas se bhar do. 🌼🍌",
    "Kele ki tarah bina shikayat ke apna kaam karo, duniya apne aap meethi ho jayegi. 🌻🍌",
    "Kele ki tarah har mausam mein apna swad banae rakhna. 🌸🍌",
    "Kele ki tarah kachhepan mein bhi ummeed rakho, ek din pakna hi hai. 🌱🍌",
    "Kele ki tarah apni mithaas ko kabhi naa becho, baant do. 🎁🍌",
    "Kele ki tarah thoda sa tedha hona bhi zaroori hai, seedha insaan to patthar hota hai. 🗿🍌",
    "Kele ki tarah duniya ki najron se chhup kar bhi meetha raho. 🌙🍌",
    "Kele ki tarah apne andar ki mithaas ko pehchano, fir koi tumhe nahi rok sakta. 🚀🍌",
    "Kele ki tarah bina kisi bhasha ke sabko samajh aana. 🗣️🍌",
    "Kele ki tarah apni jad se juda raho, tabhi meethas aayega. 🌳🍌",
    "Kele ki tarah waqt aane par khud hi toot kar baant do, yahi zindagi hai. 🌊🍌",
    "Kele ki tarah kabhi apni mithaas par sandeh mat karo, woh tumhari takat hai. 💎🍌",
    "Kele ki tarah meethas ka raaz sirf unhe pata hai jo andar utar kar dekhte hain. 🔍🍌",
    "Kele ki tarah zindagi ko meetha banana hai, toh thoda sa pyaar aur thoda sa dhairya chahiye. 💖⏳🍌",
    "Kele ki tarah apni mithaas ko kabhi kam mat samjho, ek kela bhi bhookh mita sakta hai. 🍌❤️",
    "Zindagi bhi kele ki tarah hai, kabhi seedhi nahi hoti, par muskurati hui zaroor lagti hai. 🍌✨",
"Chhilka chahe jitna bhi sakht ho, andar ki mithaas tumhare swabhav pe nirbhar karti hai. 🍌💛",
"Kaale daag toh kele pe bhi hote hain, par uski keemat uski mithaas se hoti hai, daagon se nahi. ✨🍌",
"Waqt ke sath pakna seekho, kachha kela sirf kasaila lagta hai. ⏳🍌",
"Kele ke chhilke se fisalna buri baat nahi, fisal ke na uthna buri baat hai. 😉🍌",
"Ek guchhe mein rahoge toh mehfooz rahoge, akele kele ko toh koi bhi chheel deta hai. 🤝🍌",
"Jaise kele ko chheelne par hi asli swaad milta hai, waise hi insaan ko samajhne ke liye uske aavran ko hatana padta hai. 🍌❤️",
"Zindagi ek kachhe kele ki tarah hai, thoda sabar rakhoge toh mithaas khud ba khud aa jayegi. 🌱🍌",
"Bahar se beshak daagdar dikho, par andar ka dil hamesha pake hue kele sa naram aur meetha hona chahiye. 🍌😇",
"Rang hara ho ya peela, kele ka asli wajood toh uska poshan hai. Insaan ki pehchaan bhi uske karm se hoti hai. ✨🍌",
"Teda hone ka matlab galat hona nahi, kela humein sikhata hai ki thodi fikr kam aur muskurahat zyada honi chahiye. 🍌😊",
"Rishtey kele ke guchhe jaise hote hain, ek baar alag hue toh jaldi kharab ho jate hain. 👨‍👩‍👧‍👦🍌",
"Duniya kehti hai daag achhe nahi, par pake hue kele ke daag uski asli mithaas ka saboot hain. 🍌🌟",
"Kele ko fridge mein rakhne se wo kaala ho jata hai, waise hi rishton mein zyada sardi (ego) aane se wo toot jate hain. ❄️🍌",
"Agar raaste mein kele ka chhilka mile, toh koso mat, use hata do taaki koi aur na gire. Yehi insaniyat hai. 🚶‍♂️🍌",
"Apne andar ke dar ko kele ke chhilke ki tarah utaar fenko, manzil andar chhupi mithaas ki tarah intezaar kar rahi hai. 🍌🚀",
"Zindagi jab tumhe kela de, toh complain mat karo, uska milkshake banao aur chill karo! 🥤🍌😎",
"Har hara kela ek din peela hota hai, apni mehnat par vishwas rakho, tumhara waqt bhi aayega. ⏳🍌",
"Kela sikhata hai ki zindagi mein chahe kitne bhi daag lag jayein, apni andar ki goodness mat khona. 🍌💛",
"Jo mithaas kele mein bina kisi awaz ke hoti hai, wahi shanti ek suljhe hue insaan mein hoti hai. 🧘‍♂️🍌",
"Kela jitna naram hota hai, utni hi jaldi ghul jata hai. Zindagi mein bhi thodi narmi rakho, sabke dilon mein bas jaoge. 🍌❤️",
"Thoda teda chalna bhi zaroori hai dosto, warna log seedha samajh kar asani se chheel denge. 😉🍌",
"Kisi ko bahar ke chhilke se judge mat karo, kya pata andar ka insaan kitna meetha ho. 🍌🧐",
"Waqt se pehle chheeloge toh swaad nahi milega, har cheez ka ek sahi samay hota hai. ⏱️🍌",
"Gusse mein insaan kachhe kele jaisa hota hai, na khud ko fayda deta hai na dusron ko. 😠🍌",
"Agar life smooth nahi chal rahi, toh samajh lo kela abhi pak raha hai. 🍌✨",
"Kele ki mithaas batati hai ki shanti aur dhairya ka fal hamesha meetha hota hai. 🍌🕊️",
"Jaise kela har mausam mein milta hai, waise hi sachha dost har haal mein sath khada milta hai. 🤝🍌",
"Khud ko itna sasta mat banao ki log kele ki tarah tumhe easily use kar lein, apni value samjho. 🍌💎",
"Ek pake hue kele ki khushboo use chhupne nahi deti, waise hi tumhari mehnat ek din sabko dikh jayegi. 🍌🌟",
"Zindagi kele ki tarah tedi-medi hoti hai, bas chhilka utaro aur mithaas ka anand lo. 🍌🎢",
"Daagdar kela aur tajurbedaar insaan, dono hi andar se bohot keemti hote hain. 🍌🧠",
"Kele ki tarah bano—bahar se surakshit, andar se naram aur doosron ko energy dene wale. 🍌⚡",
"Gire hue kele ke chhilke se seekho, jo apni ahmiyat khota hai wo dusron ko gira hi deta hai. 🍌⚠️",
"Ek sachhi dosti us kele ki tarah hoti hai jo guchhe mein sabse aakhiri tak juda rehta hai. 🍌🔗",
"Hara kela ummeed hai, peela kela safalta, aur kaala kela anubhav. 🍌📈",
"Tumhari asli khoobsurti tumhari aatma mein hai, theek waise jaise kele ki asli mithaas chhilke ke andar hoti hai. 🍌💖",
"Kela ek aam fal hokar bhi khaas hai, kyunki wo sadgi mein hi apni taqat chhupaye rakhta hai. 🍌💪",
"Jisne kele ko theek se chheelna seekh liya, usne zindagi ki mushkilon ko hal karna seekh liya. 🍌🛠️",
"Chhilka badrang ho sakta hai, par andar ki niyat hamesha pake kele jaisi saaf honi chahiye. 🍌🤍",
"Agar kismat tedi hai, toh muskurakar kaho, 'Kela bhi toh teda hota hai, par meetha kitna lagta hai!' 🍌😂",
"Jaise guchhe mein ek kharab kela baakiyon ko kharab kar deta hai, waise hi ek negative soch poori life kharab kar sakti hai. 🍌🚫",
"Sabar ek kachhe kele ko peela karta hai, aur jaldbaazi use kaala. Faisla tumhara hai. 🍌⏳",
"Apni galtiyon ko kele ke chhilke ki tarah maano—unse thokar khao, par phir dhyan se aage bado. 🍌🚶‍♂️",
"Dusron ko girane ki koshish mat karo, chhilke aksar apne hi kadmon ke neeche aa jate hain. 🍌👣",
"Zindagi mein do hi options hain: ya toh chhilka bankar phek diye jao, ya kela bankar kisi ko taqat do. 🍌💥",
"Har tedi cheez galat nahi hoti, aasmaan ka chand aur kela dono is baat ka saboot hain. 🌙🍌",
"Kele ki mithaas chakhne ke liye use chheelne ka dard toh dena hi padta hai. Bina struggle ke success nahi milti. 🍌✨",
"Jaise kela sasta hokar bhi ameer aur gareeb dono ki bhookh mitata hai, waise hi insaniyat sabke liye barabar honi chahiye. 🍌🤝",
"Bahar ke daag dekh kar kele ko nakarne wale, aksar sabse behtareen mithaas chook jate hain. 🍌👀",
"Khushiyan baantne se badhti hain, bilkul ek darjan kele ki tarah—akela kya hi kar loge, sabke sath baanto! 🍌🍌",
"Zindagi ko kele ki tarah simple rakho—na koi beej ka jhanjhat, na koi pareshani, bas khao aur khush raho. 🍌😌",
"Kela bina chhilke ke jaldi kharab ho jata hai, waise hi insaan bina apno ki dhaal ke weak pad jata hai. 🍌🛡️",
"Thodi flexibility rakhna seekho, straight lines boring hoti hain, thoda banana curve zaroori hai. 🍌〰️",
"Paka hua kela apne guchhe mein jhuk jata hai, maturity humein bhi jhukna aur humble rehna sikhati hai. 🍌🙏",
"Agar aaj life tumhe kele ka chhilka dikha rahi hai, toh shukriya kaho, shayad aage koi bada gaddha ho jisse tum bach gaye. 🍌🛤️",
"Kele sa dil rakho, jo kisi ke dukh mein asani se pighal jaye. 🍌❤️",
"Mehnat ka kela hamesha meetha hota hai, muft ka kela sirf aalas badhata hai. 🍌🏋️‍♂️",
"Jo kela kachha tod liya jata hai, wo artificially pakta toh hai, par usme natural mithaas nahi hoti. Fake mat bano. 🍌🎭",
"Kele ka ped ek baar hi fal deta hai, isliye apna best shot do, kal kisne dekha hai! 🍌🌱",
"Tedi baatein karne walo ko tedi muskaan se ignore karo, yahi hai asli kela philosophy! 🍌😏",
"Kele mein seed nahi hote, wo dilon mein seedha utarta hai. Aapki baatein bhi aisi hi bina chubhan wali honi chahiye. 🍌🗣️",
"Andar ki positivity ko kele ke chhilke ki tarah wrap karke rakho, taaki bahar ki negativity use choo na sake. 🍌✨",
"Zindagi ek banana split ki tarah hai, alag alag flavors hain, bas tumhe enjoy karna aana chahiye. 🍌🍨",
"Kachhe kele ka chips aur pake kele ka shake—zindagi ke har phase mein dhalna aur jashn manana seekho. 🍌🥳",
"Chhilka kitna bhi mota ho, mithaas aakhir mein apni jagah bana hi leti hai. 🍌💪",
"Overthink mat karo, zindagi kele jaisi aasaan hai, faltu mein use anar mat banao jisme itne daane hon! 🍌😂",
"Duniya ke daagdar tanon se darna mat, wo sirf tumhara chhilka hain, tumhari asli pehchan nahi. 🍌🙅‍♂️",
"Ek akela kela kitni bhi koshish kare, guchhe jaisi taqat nahi pa sakta. Unity mein hi strength hai. 🍌💪",
"Kele sa soft bano apnon ke liye, aur chhilke sa slippery unke liye jo tumhe girana chahein. 🍌😎",
"Sacha pyar us aakhiri kele ki tarah hota hai jise sab chhod dete hain, par wahi sabse meetha nikalta hai. 🍌💕",
"Apne iradon ko kachhe kele sa majboot rakho aur dil ko pake hue kele sa naram. 🍌❤️‍🔥",
"Kele ki koi awaz nahi hoti jab wo pak raha hota hai. Apni success ko aawaz karne do, mehnat khamoshi se karo. 🍌🤫",
"Koi fruit itna humble nahi jitna kela, jo apna chhilka khud hi asani se utaarne deta hai. Ego mat rakho. 🍌🙌",
"Jis tarah kela instant energy deta hai, waise hi tumhari ek choti muskurahat kisi ki thakan mita sakti hai. 🍌⚡",
"Zindagi ke safar mein thoda tedi-medi raahon se guzarna padega, tabhi mithaas ki real value samajh aayegi. 🍌🛣️",
"Kele ko force se chheeloge toh toot jayega, pyar se chheeloge toh pura milega. Rishtey bhi aise hi hote hain. 🍌🤲",
"Guchhe se alag hone par kela jaldi pak jata hai, akelepan mein insaan bhi jaldi bada ho jata hai. 🍌👤",
"Ek chhilka akele ek insaan ko gira sakta hai, socho ek meetha kela kitno ka din bana sakta hai! 🍌🌟",
"Khud ko banana bread ki tarah badalna seekho—jab lage ki overripe ho rahe ho, toh naya aur behtar roop le lo. 🍌🍞",
"Jaldbaazi mein kachha kela khakar muh mat banao, zindagi aur waqt dono par thoda sabar rakho. 🍌🕰️",
"Kele ki sabse badi khasiyat uski simplicity mein hai. Ameer banne ki hod mein apna sadapan mat khona. 🍌🌿",
"Kabhi kabhi kaale daag sirf is baat ka ishara hote hain ki ab waqt aa gaya hai apni asli sweetness dikhane ka. 🍌🔥",
"Chhilke pehle nikale jate hain, mithaas baad mein aati hai. Success ka bhi yahi rule hai, pehle rough phase jhelna padta hai. 🍌🏆",
"Zindagi mein khud ko 'Banana' (behtar ban-na) zaroori hai, taaki log tumhe dekhkar inspire ho sakein. 🍌😜",
"Kele ka aakar muskaan jaisa hai, aur mithaas shehad jaisi. Insaan mein bhi sundarta aur gun dono sath hone chahiye. 🍌🌙",
"Gira hua kela peechhe chhut jata hai, par guchhe ka hissa aage badhta hai. Hamesha apno ke sath milkar chalo. 🍌🚶‍♂️🚶‍♀️",
"Ek kela kabhi dusre kele jaisa exactly same nahi hota, apni is uniqueness ko embrace karo aur aage bado. 🍌✨",
"Zindagi ki har kadwahat ko door karne ke liye hamesha apne paas kele jaisi mithi umeed rakho. 🍌🌈",
"Chhilke ko zameen pe fenkna aadat hai, usko dustbin mein dalna tarbiyat. Apne karm sudharo, duniya sudhar jayegi. 🍌🗑️",
"Kele ki curve humein batati hai ki perfection ek myth hai, real beauty imperfections mein hi chhupi hoti hai. 🍌🎨",
"Jis fruit mein seed nahi, wo bhi kitna asar chhodta hai. Apne actions se asar chhodna seekho, be impactful like a banana. 🍌🌍",
"Jab sab sath chhod de, toh akele baithkar banana milk-shake pee lena, dimag thanda aur dil meetha ho jayega! 🍌🥤",
"Kele ko chhupana mushkil hai uski khushboo se, waise hi acche insaan ki achhai bhi khud bahar aa hi jati hai. 🍌🌬️",
"Hara, Peela, Kaala—zindagi ke har badalte rang ko swikar karna hi asli samjhdari hai. 🍌🎨",
"Jo kela zyada meetha hota hai, aksar usipe zyada daag hote hain. Tumhara dard aur struggle hi tumhari asli strength hai. 🍌💪",
"Kuch log kele ke chhilke jaise hote hain, unka maqsad sirf aapke raaste mein aakar aapko girana hota hai. Unse bach kar chalein. 🍌🚧",
"Apni kshamta ko pehchano, tum ek kela ho jo kisi thake hue musafir ki subah ki energy ban sakta hai. 🍌🌅",
"Zindagi mein sabse bada lesson kela deta hai: Andar se meetha aur saaf raho, chahe bahar ki duniya kitni bhi tough kyun na ho. 🍌🌍",
"Kela bankar kisi ke chehre par muskaan lao, dukh toh waise bhi duniya ke chhilke roz de hi dete hain. 🍌😊"
"Zindagi ek kele ki tarah hai, bahar se chahe kitni bhi sakht ho, andar se hamesha naram aur meethi honi chahiye. 🍌✨",
    "Jo kela waqt se pehle pakne ki koshish karta hai, wo aksar swaad kho baithta hai. Sabra rakho, tumhara waqt aayega. ⏳🍌",
    "Chhilke par fisalna tumhari galti nahi, par fisal kar wahin gire rehna tumhari haar hai. Utho aur aage badho! 🏃‍♂️🍌",
    "Guchhe mein rehne wale kele kabhi akele nahi padte. Apno ka sath hamesha mazbooti deta hai. 🤝🍌",
    "Kele ka tedhapan hume sikhata hai ki zindagi hamesha seedhi nahi chalti, uske mod ko apnana padta hai. 🛤️🍌",
    "Kaale daag dekh kar kele ko mat phekna, aksar sabse meetha swaad unhi mein chhipa hota hai. Tajurbe ki kadr karo. 🤎🍌",
    "Jaise kela apna chhilka utaar kar asliyat dikhata hai, waise hi insaan ko apne guroor ka chhilka utaarna chahiye. ✨🍌",
    "Akela kela jaldi kharab ho jata hai, par guchha lamba tikta hai. Ekta mein hi asli zindagi hai. 🌿🍌",
    "Kela kitna bhi aam kyun na lage, bhookh mitane mein uska koi mukabla nahi. Sadgi mein hi asli taqat hai. 💪🍌",
    "Har kele ko pakne ke liye waqt chahiye. Khud ko doosron se compare mat karo, tumhari mithaas apni hai. 🌟🍌",
    "Kele ki mithaas uske rang par nahi, uske pakne par nirbhar karti hai. Insaan ko uski shakal se nahi, uske dil se pehchano. ❤️🍌",
    "Agar zindagi kela de, toh complain mat karo, uska milkshake banao aur enjoy karo! 🥤😉",
    "Chhilke sa dikhawa kab tak karoge? Asli maza toh andar ki mithaas mein hai. 🍌🎭",
    "Zindagi agar terhi bhi lage toh ghabrana mat, kela bhi terha hota hai par swaad mein behtareen. 🌈🍌",
    "Kuch kele kachhe achhe lagte hain, kuch pakke. Zindagi ke har phase ka apna alag hi maza hai. 🌱🍌",
    "Gire hue chhilke par dusro ko girana aasan hai, par us chhilke ko raste se hatana hi asli insaniyat hai. 🚶‍♂️🍌",
    "Kela aur rishte dono naram hote hain, thodi si bedardi se dono par nishaan pad jate hain. Sambhal kar rakhein. 💔🍌",
    "Dusro ki chhatri banne se pehle, kele ke patte ki tarah khud ko itna bada banao ki sabko saya de sako. 🍃🍌",
    "Jaldbaazi mein kachha kela mat khao, thoda intezaar karoge toh mithaas doguni milegi. Sabr ka fal kela hota hai! 😌🍌",
    "Jaise kela bina beej ke bhi ek poora ped khada kar deta hai, waise hi bina shor machaye apne kaam se pehchaan banao. 🌳🍌",
    "Ek sadta hua kela pure guchhe ko kharab kar sakta hai. Apni sangat hamesha soch samajh kar chuno. 🧠🍌",
    "Kele ki aukaat chhilka utarne ke baad pata chalti hai, aur insaan ki aukaat waqt aane par. ⏳🍌",
    "Duniya tumhe tumhare daag se judge karegi, par tum apni mithaas par bharosa rakhna. 🌟🍌",
    "Zindagi ke safar mein thoda lachila hona zaroori hai. Kadak rahoge toh toot jaoge, kele ki tarah terhe rahoge toh fit rahoge. 🛤️🍌",
    "Kele ke chhilke si ban gayi hai ye zindagi, kab kahan fisal jaye pata hi nahi chalta. Par mazaa bhi isi mein hai! 😅🍌",
    "Chot khaya hua kela andar se sabse zyada meetha hota hai. Zindagi ke dard tumhe aur behtar banate hain. ❤️‍🩹🍌",
    "Guchhe se alag hokar kela jaldi pak jata hai. Akelepan mein insaan waqt se pehle bada ho jata hai. 🚶‍♂️🍌",
    "Kela ped se alag hokar bhi logo ke kaam aata hai. Tumhara maksad bhi sirf badhna nahi, kisi ke kaam aana hona chahiye. 🤲🍌",
    "Zindagi mein 'Kela' bano, jo sasta zaroor hai par har ameer aur gareeb ki thali mein barabar izzat pata hai. 👑🍌",
    "Jab zindagi akelepan mein ghutne lage, toh yaad rakhna akele kele ki bhi badi demand hoti hai. Tum khaas ho! ✨🍌",
    "Kele jaisi fitrat rakho, koi chil ke khaye toh meetha lago, koi daba de toh milkshake ban jao. Adaptability is key! 🥤🍌",
    "Jo kela kachha hota hai woh bhi sabji ban kar kaam aata hai. Tumhari aehmiyat kabhi khatam nahi hoti, bas waqt badalta hai. 🍲🍌",
    "Daag dar kele se seekho—jo cheez perfect nahi dikhti, zaroori nahi ki wo bekar ho. 🤎🍌",
    "Chhilka kitna bhi chamakdar kyun na ho, dil tabhi jeeta jata hai jab andar ka kela meetha ho. ✨🍌",
    "Zindagi ko us chhilke ki tarah mat banao jise log utaar kar phek de. Zindagi us mithaas ki tarah jiyo jo logo ke dilo mein bas jaye. ❤️🍌",
    "Tera waqt aayega, ye bas ek process hai. Hara kela bhi toh ek din peela aur meetha hota hai. 🌱➡️🍌",
    "Thodi sadgi laao apne mizaaj mein, ped pe laga kela bhi niche jhuk kar hi waqt guzarta hai. 🌿🍌",
    "Agar log tumhe dabane ki koshish karein, toh kele ki tarah itne naram ban jao ki unke hi hathon mein bikhar kar sweet ho jao. 😊🍌",
    "Koi chhilke ko chot pahunchaye, tum apni mithaas par aanch mat aane dena. Khud ko itna mazboot rakho. 💪🍌",
    "Har mausam mein milta hai kela. Tum bhi us dost ki tarah bano jo har haal mein dosto ke saath khada rahe. 🤝🍌",
    "Guchhe ki takat ekta mein hai. Ek bar tut gaye toh bikne ka daam gir jata hai. Parivar ke sath raho. 👨‍👩‍👦🍌",
    "Tera rang chahe hara ho, peela ho ya kala, tu khud mein mukammal hai mere dost. 🌟🍌",
    "Zindagi kabhi seedhi line mein nahi chalti. Kele ka curve bhi yahi kehta hai ki har mod pe ek naya swaad hai. 🎢🍌",
    "Jab tak chhilka nahi utrega, khushboo bahar nahi aayegi. Apne darr ka chhilka utaaro aur duniya ko apni kableeyat dikhao. 🚀🍌",
    "Zindagi ke raste mein kele ke chhilke milenge zaroor. Bas girne se darna mat, gir kar hi chalna seekhoge. 🚶‍♂️🍌",
    "Kela kabhi apni shakal par ghamand nahi karta. Kyunki use pata hai ki uski asal pehchaan uski mithaas hai. 😌🍌",
    "Jaisa darpan mein kela dekhta hai, waise hi hum khud ko dekhte hain. Jaisa socho ge, waise ban jaoge. 🪞🍌",
    "Kuch rishte kele aur doodh jaise hote hain, alag alag achhe lagte hain par saath mil jaye toh shake ban jate hain. 🥛🍌",
    "Duniya ki nazar mein kela ek aam fal hai, par bimar ke liye wahi sanjeevani hai. Apni value sahi jagah pehchano. 🏥🍌",
    "Kele ka phool (banana flower) andar se hamesha mehfooz rehta hai. Apne dil ko bhi duniya ki kadwahat se aise hi mehfooz rakho. 🌺🍌",
    "Kacha kela pakne ka sabr dikhata hai. Jaldbaazi karoge toh sirf kadwahat hath aayegi. 🧘‍♂️🍌",
    "Chhilke ko aukaat mat dikhao, wo zameen par aakar bade bado ko gira sakta hai. Kisi ko chhota mat samjho. 😏🍌",
    "Zindagi mein agar daag lag bhi jayein, toh kya? Kala pad chuka kela sabse aasaani se mash hota hai aur smoothie ke kaam aata hai. 🥤🍌",
    "Jis tarah kela andar se pure (safed) hota hai, waise hi apna zameer hamesha saaf rakhna chahiye. ✨🍌",
    "Kele ka guchha sikhata hai ki apno ke sath chipke rehne mein hi bhalai aur aukaat hai. 🤗🍌",
    "Jo toot gaya wo alag ho gaya. Par jo tut kar bhi kaam aaye, wo asal kela hai. Zindagi mein hamesha useful bano. 💡🍌",
    "Kela aur kirdaar dono mein daag jaldi lagte hain, inki hifazat bohot nazakat se karni padti hai. 🎭🍌",
    "Tere wajood ki ahmiyat is baat se nahi ki tu kaisa dikhta hai, balki is baat se hai ki tu kitni bhookh mitata hai. 🌍🍌",
    "Kele ko force se pakaoge toh swaad mein maza nahi aayega. Life ke lessons naturally seekhne do. 🌱🍌",
    "Ek sadharan sa kela subah ki best shuruwat ho sakta hai. Chhoti chhoti cheezon mein badi khushiyan dhoondo. 🌅🍌",
    "Kabhi fisal jao toh khud par hasna seekho, rona nahi. Kele ka chhilka bhi hume muskurana hi sikhata hai. 😂🍌",
    "Chhilka utarne ke baad hi kela dusro ke kaam aata hai. EGO chhodoge, tabhi respect milegi. 🙌🍌",
    "Zindagi bhi aisi hi hai, jo hissa thoda zyada naram ho jata hai, log sabse pehle usko nikal fekte hain. Mazboot bano. 🧱🍌",
    "Kele ki tarah bano, jise khane mein zyada mehnat na lage. Apni baato ko simple aur dil se nikli hui rakho. 🗣️🍌",
    "Kele jaisa ban jao, na chillane ki zaroorat, na dikhawa karne ki. Jo samajhta hai, wo apne aap chhilka utar lega. 🤫🍌",
    "Guchhe ko thode dabaw mein pakadna zaroori hai. Rishto mein thoda control pyar banaye rakhta hai. ❤️🍌",
    "Waqt har kachhe kele ko meetha kar deta hai, tumhara bhi dard ek din tumhari taqat ban jayega. 💪🍌",
    "Kisi ki zindagi mein kele ke chhilke ki tarah rukawat mat bano, ban sako toh uske safar ka energy booster kela bano. ⚡🍌",
    "Kele ki sadgi uski weakness nahi, uska aakarshan hai. Dikhawe ke is zamane mein simple hona bhi ek art hai. 🎨🍌",
    "Zindagi seedhi line ki tarah boring nahi honi chahiye, isme kele ki tarah thoda curve, thoda twist hona chahiye! 🎢🍌",
    "Duniya bhale hi seb aur aam ki deewani ho, par saste aur sabse zaroori waqt ke sathi toh kela hi hota hai. 🤝🍌",
    "Insaan ko hamesha kele ke ped jaisa hona chahiye, ek bar fall do, par jee bhar ke do aur sub kuch nyochhawar kar do. 🌳🍌",
    "Chot lage toh kela jaldi kaala pad jata hai. Sensitive log jaldi bura maan jate hain, unhe pyar se handle karein. 🩹🍌",
    "Akela hokar bhi kela apni puri pehchaan rakhta hai. Apni individuality par garv karna seekho. 👑🍌",
    "Jis par log haskar fisalte hain, wahi chhilka kabhi fruit ko protect karta tha. Kisi ki past value ko under-estimate mat karo. 🛡️🍌",
    "Kela hume yeh sikhata hai ki har khoobsurat cheez ka aakhiri hissa (tip) thoda kadwa/kasaela ho sakta hai, aur yeh theek hai. 🍂🍌",
    "Kele ki fitrat uske patto mein chhipi hai, lambi, chaudi aur sabko chhawn dene wali. Apni neeyat bhi aisi hi rakho. 🍃🍌",
    "Zindagi ka asool kele jaisa hai: jo andar se achha hoga, wahi bahar se khilega. ✨🍌",
    "Har cheez ka apna waqt hota hai, hara kela khakar mithaas ki umeed nahi kar sakte. Patience is key. ⏳🍌",
    "Bahar ke dag se andar ki mithaas kam nahi hoti. Zindagi mein aayi mushkilein tumhara dil chota nahi kar sakti. ❤️🍌",
    "Duniya jab takat ka display karti hai, kela bas aaram se chupke baithe rehta hai. Real winners don't show off. 🏆🍌",
    "Thode daag kya lag gaye zindagi mein, logo ne phek diya. Par bake hone par wahi banana bread sabse tasty banegi! 🍞🍌",
    "Zindagi ka balance uske guchhe mein hai, ek taraf jhukoge toh sab toot jayenge. Balance banaye rakho. ⚖️🍌",
    "Kela apni jagah kabhi nahi badalta par apna rang badalta hai, samajhdar log bhi waqt ke sath grow karte hain. 🌱🍌",
    "Us kele ki tarah raho jisko dekhte hi pata chal jaye ki swaad kaisa hoga, transparent aur sacha! 🔍🍌",
    "Agar aapko lagta hai kela aam sa fruit hai, toh workout ke baad uski value poochho. Har insaan ki ahmiyat uske sahi samay par hoti hai. 🏋️‍♂️🍌",
    "Jo kela guchhe se toot kar jaldi pakna chahta hai, wo sikhata hai ki shortcut hamesha jaldi kharab bhi karte hain. ⏱️🍌",
    "Jab tak chhilka apne kele ko nahi chhodta, tab tak kela mitti mein nahi milta. Rishto ko ant tak nibhao. 🤗🍌",
    "Kisi bhi problem par zyada der tak rona, kele ko fridge mein rakhne jaisa hai. Jaldi kaala pad jayega! 🥶🍌",
    "Kele sa lachila pan apni baato mein rakhna, koi galat samjhe toh tod kar mithaas baat dena. 🕊️🍌",
    "Har kisi ko apne daag mat dikhao, kya pata koi banana mash banane ka soch raha ho. Apne dard ko apni taqat banao. 🤫🍌",
    "Tera kirdar kele sa hona chahiye, bahar ek security aur andar ek mithaas ka dariya. 🌊🍌",
    "Kele ke chhilke par sab fisalte hain, par wahi chhilka compost ban kar naye podho ko zindagi deta hai. Mistakes fuel growth. 🌱🍌",
    "Guchhe ka har kela ek jaisa nahi hota. Kuch terhe, kuch seedhe. Par sath milkar wo pure hote hain. Diversity in unity! 🌍🍌",
    "Tera hara hona teri nadani nahi, teri shuruaat hai. Khud ko pakhne ka poora waqt do. ⏳🍌",
    "Sab kuch khatam bhi ho jaye toh kele ki tarah end mein ek sweet memory zarur chhod ke jana. ✨🍌",
    "Tera terhapan tera imperfection nahi, tera unique signature hai. Duniya ko seedha hone ka natak karke mat dikhao. 🖊️🍌",
    "Log tumhe nichodna chahenge, par yaad rakhna kela kabhi juice nahi banta, wo hamesha substance deta hai. Be solid! 💪🍌",
    "Akele pan mein bhi wahi mithaas maintain rakho jo guchhe mein thi, tumhara kirdar kisi ka mohtaj nahi. 🌟🍌",
    "Zindagi ek kela hai, iska swaad lo, iske chhilke se bacho aur end mein khushi ka ek tukda ban kar raho! 🎉🍌"
]

