# poems.py

BANANA_POEMS = [
    "Peela peela pyara kela,\nSab phalon mein yeh albela.\nChhilka utaro, gup-chup khao,\nSwad iska sabko batao! 🍌🎶",
    "Bandar mama ko bhaya kela,\nDekhte hi lagaya mela.\nEk khaya, dusra khaya,\nFir pet pakad kar zor se chillaya! 🐒🍌",
    "Aam ka raja bhale hi naam ho,\nPar kele bina sab nakaam ho.\nSubah khao ya khao sham,\nKela hi karta hai saara kaam! 🍌❤️",
    "Kela khana aasaan bada,\nNa dhona na kaatna pada.\nChhilka utaro aur chupchap khao,\nApni saari thakan mitao! 🍌😎",
    "Chhilka iska mat girana,\nVarna padega tumhe pachtana.\nPaer padega fisal jaoge,\nHaddi tootegi tab rote aaoge! 🍌🏥",
    "Gym mein jaa kar uthaya bhaar,\nKela khaya maine baar baar.\nBody meri ban gayi bhai,\nKele ne hi yeh shaan badhai! 💪🍌",
    "Gusse mein jab GF aayi,\nMaine turant kela khilaai.\nGussa uska ho gaya chhoo,\nKela ban gaya taranhar bro! 🍌💖",
    "Saste mein ye mil jata hai,\nSabke mann ko bhata hai.\nGarib amir sab khate hain,\nKele ke hi gun gaate hain! 🍌🎶",
    "Fridge mein isko mat rakhna,\nKaala padega bura lagega chakhna.\nBahar rakho aur masti se khao,\nKele ka tum jashn manao! 🍌🎉",
    "Subah subah jab bhookh sataaye,\nChimpu daud ke kela khaaye.\nPet mein ja kar dhoom machaaye,\nChehre par muskaan le aaye! 🐒🍌",
    "Kela hai mera sabse pyara,\nIsne diya mujhe bada sahara.\nBina daant ke ise chabao,\nMasti se tum isko khao! 🍌🥰",
    "Bandar ki hai ek hi maang,\nKele de do mat karo tang.\nAgar nahi doge tum kela,\nMach jayega yahan bada jhamela! 🐒🍌🔥",
    "Seb santra sab hain bekaar,\nKele se hi hai mera saccha pyaar.\nGol gol nahi ye lamba lamba,\nKhakar ban jao tum khamba! 🍌🤣",
    "Duniya gol hai kisne bola,\nDuniya toh hai kele ka jhila.\nThodi tedhi par badi meethi,\nKele jaisi hai ye niti! 🍌🌍",
    "Kela khakar main so gaya,\nSapno mein bhi kela kho gaya.\nSapne mein aaya ek bada kela,\nBola chal ab laga le mela! 🍌😴",
    "Doctor ne jab mujhko toka,\nBola kela khana bada dhoka.\nMaine doctor ko kela khilaya,\nWo bhi kele ka deewana ban gaya! 🍌👨‍⚕️",
    "Zindagi meri akele thi,\nKismat meri paheli thi.\nPhir ek din mujhe kela mila,\nKhushiyon ka jaise phool khila! 🍌🌸",
    "Chhilka utarna ek kala hai,\nKela toh sabka bhala hai.\nAdha chhilka latka ke khao,\nStyle apna tum sabko dikhao! 🍌✨",
    "Kela milk ka banta shake,\nIske aage fail hai cake.\nEk glass jab andar jaaye,\nBacha bacha thumke lagaye! 🍌🥤",
    "Ek din maine kela churaya,\nPiche piche maalik aaya.\nMaine jaldi se chhilka feka,\nMaalik gira aur maine dekha! 🍌🏃‍♂️",
    "Paanch rupaye mein ek kela,\nDekho iska kaisa khela.\nSasta sundar aur tikau,\nIsko khakar ban jao bhau! 🍌💰",
    "Kele ki hai baat nirali,\nIsne meri duniya badali.\nRoz khao tum kela bhai,\nKabhi na leni padegi dawai! 🍌💊",
    "Shaadi mein jab aaya kela,\nDulhan ne bhi chhod diya mela.\nBoli rasgulla nahi khana,\nMujhe toh bas kela hai chabana! 🍌👰",
    "Exam mein jab dimaag na chala,\nMaine chupke se khaya kela.\nAchanak se yaad aaya sab,\nTeacher bhi boli ye kaisa kartab! 🍌📚",
    "Kela jab gusse mein aaya,\nApni jacket ko jaldi utarvaya.\nBola ab main nahi rukunga,\nSidha pet mein hi ghusunga! 🍌😡",
    "Mummy boli beta fruit kha le,\nKele ke tu maje utha le.\nMaine khaye pure darjan,\nMummy ne kiya phir mera visarjan! 🍌🧹",
    "Kele ke upar kaale daag,\nDekh kar mujhko lagti aag.\nPar khane mein hota hai meetha,\nJaise gaon ka koi geetha! 🍌🔥",
    "Aasman mein jaise chamke tara,\nDharti par chamke kela pyara.\nIski chamak se duniya roshan,\nKela khana hai sabse bada tution! 🍌🌟",
    "Kela kela sab chillaaye,\nPar koi isko samajh na paaye.\nAndar se ye bada naram hai,\nChhilka iska uska dharam hai! 🍌🙏",
    "Chimpu aur kela bhai bhai,\nInki jodi hai badi safai.\nEk khata hai dusra khilata,\nYe rishta hamesha muskurata! 🐒🍌🤝",
    "Rat ke baarah baje thi bhookh,\nPet raha tha sookh sookh.\nFridge se maine kela nikala,\nKhate hi ban gaya main matwala! 🍌🕛",
    "Kela khane ki ninja technique,\nSikhlo mujhse bano mat weak.\nEk hath se pakdo chhilka,\nDusre se khao ban ke halka! 🍌🥷",
    "Kele ke bina main kuch bhi nahi,\nYe aadat meri buri toh nahi.\nLog kehte hain bandar mujhe,\nKela chhodne mein kaisa mazza tujhe? 🐒🍌",
    "Tension jab dimaag ko khati,\nKela meri jaan bachati.\nEk bite mein stress out,\nKela khakar I just shout! 🍌🔊",
    "Mobile phone aur ek kela,\nBaaki sab lagta hai jhamela.\nInsta scroll aur kela bite,\nZindagi chal rahi hai ekdum bright! 🍌📱",
    "Pyar vyaar sab dhoka hai,\nKela khane ka accha mauka hai.\nDil tootega toh royega,\nKela khayega toh aaram se soyega! 🍌💔",
    "Ek din maine laya hara kela,\nSocha kaisa hoga ye khela.\nKachha kela muh mein gaya,\nSwad uska bilkul na bhaya! 🍌🤢",
    "Hara kela pakode ke kaam,\nPila kela toh mera salaam.\nKaala kela ban jata cake,\nKela hamesha karta hai make! 🍌🧁",
    "Party mein sab naach rahe the,\nKela hath mein jhaach rahe the.\nJo gira chhilka dance floor par,\nSab gire jaise machi ho tod-phor! 🍌🕺",
    "Kela mera sachcha dost,\nIsko karta hu main sabse zyada toast.\nZindagi bhar sath nibhayega,\nKela mujhko jannat dikhayega! 🍌🥂"
]

BANANA_QUOTES = [
    "Zindagi ke safar mein kele sa meetha ban,\nChhilke sa ahankaar chhod aur sacha insaan ban! 🍌✨",
    "Waqt ke sath kela pakta hai aur hota hai lajawab,\nSabr rakh mere dost, zaroor poore honge tere khwab! 🍌🌟",
    "Andar se naram aur bahar se sakht apna aavaran rakh,\nKele ki tarah tu bhi is duniya mein apni pehchan rakh! 🍌💪",
    "Kele ka chhilka sikhata hai humein girna aur sambhalna,\nMushkilon ke bawajood bhi seekho aage nikalna! 🍌🚶‍♂️",
    "Duniya tujhe tedha kahe, par tu apni mithaas mat chhod,\nKele ki tarah bina bhedbhav ke har dil se rishta jod! 🍌💛",
    "Saste mein milta hai kela, par takat iski mahan hai,\nSaadgi mein jeene walon mein hi basti asli jaan hai! 🍌🌿",
    "Chhilka utar kar dekho, kela hota bilkul saaf hai,\nSacha dil rakhne walon ke liye har chhoti galti maaf hai! 🍌🕊️",
    "Gusse ka chhilka utar de, aur andar se tu naram ban,\nKele jaisi mithaas la, aur acche apne karam ban! 🍌🧘‍♂️",
    "Akelepan se mat ghabra, kela bhi toh a-kela hai,\nKhud par tu vishwas rakh, yeh duniya ek mela hai! 🍌🎪",
    "Kele ke jaisa ban, jo har haal mein saath nibhata hai,\nChahe bimari ho ya thakan, yeh hamesha takat badhata hai! 🍌🔋",
    "Bahar se chahe daag lag jaye, par andar se safed rehna,\nKele ki tarah har musibat ko tu haste-haste sehna! 🍌😊",
    "Jab tak chhilka na utre, kele ka swaad nahi aata,\nJab tak mehnat na ho, tab tak koi safal nahi ban pata! 🍌🏆",
    "Peele rang ka kela jaise roshan karta hai din,\nWaise hi mehnat ke bina aati nahi safalta tere bin! 🍌☀️",
    "Sasta samajh kar kele ko tu kabhi na bekar maan,\nIs chhote se phal mein chhupi hai badi-badi jaan! 🍌🔥",
    "Kele ko dekho, bina guroor ke ped par latakta hai,\nJo jhukta hai nirmalta se, wahi asmaan ko chhoota hai! 🍌🌳",
    "Jaise kela deta hai fauran nayi urja ka ehsaas,\nWaise hi hamesha zinda rakh apne andar ki aas! 🍌⚡",
    "Tedha hokar bhi kela sabko meetha lagta hai,\nSacchi niyat ho toh har koi accha lagta hai! 🍌💖",
    "Kele jaisa naram dil rakh, kisi ko na tu sata,\nApni acchai se is duniya mein naya itihaas bana! 🍌📖",
    "Kele ko chheelne par milti hai andar ki mithai,\nBina parishram kiye kabhi kisi ne manzil nahi pai! 🍌🏔️",
    "Har din ek kela kha, aur apne lakshya par dhyan laga,\nKathinaiyon se mat darr, bas aage kadam badha! 🍌🚀",
    "Kela nahi dekhta ki tu ameer hai ya gareeb,\nMehnat karne walo ke hi aate hain khushiyan qareeb! 🍌💰",
    "Kele ke ped ka har hissa kaam mein aata hai,\nParopkar se hi manushya mahaan ban jata hai! 🍌🌿",
    "Bahar ka roop kaisa bhi ho, aatma ko tu shuddh rakh,\nKele ki tarah har haal mein apne vicharon ko buddh rakh! 🍌🧠",
    "Jaise kela mita deta hai bhookh pal bhar mein,\nWaise hi tu laa khushiyan sabhi ke ghar mein! 🍌🏡",
    "Kele ki tarah mithaas ban kar sabki zindagi mein ghul ja,\nApne ahankaar ko bhool kar sabke dilon se mil ja! 🍌💞",
    "Kele ka chhilka giraye, par kela takat de jaye,\nZindagi mein jo sikh le is se, wo har mushkil par vijay paye! 🍌🏅",
    "Kele ka ped bina beej ke bhi apna vistar karta hai,\nSachha gyaan wahi hai jo khud ko jagruk karta hai! 🍌🌱",
    "Chahe ho upvaas ya tyohar, kela hamesha paas hai,\nSacche dost ki tarah yeh rishta bada hi khaas hai! 🍌🤝",
    "Bina daant wala bhi kele ko aaram se khata hai,\nSaralta se hi insaan sabke dilon par chha jata hai! 🍌👴",
    "Kele ki khushboo se jaise mehek jata hai aas-paas,\nWaise hi apne karmon se paida kar ek naya vishwas! 🍌🌬️",
    "Kaala padne par bhi kela meetha cake banata hai,\nBure waqt mein bhi accha insaan raasta nikal hi lata hai! 🍌🎂",
    "Kele ki tarah apna mol kabhi na girne de,\nSamay aane par sabko tu apni chamak dikhne de! 🍌✨",
    "Ek kela aur ek muskaan, dono mein hai ajeeb si shakti,\nInke bina adhuri hai is jeewan ki bhakti! 🍌🙏",
    "Kele ka guchha sikhata hai ekta ki pehchan,\nMil kar rehne mein hi chhupi hai sabki shaan! 🍌🤜🤛",
    "Jaise kela jald hi hazam ho kar asar dikhata hai,\nAccha vichaar bhi turant man ko shanti dilata hai! 🍌🕊️",
    "Bina aawaz kiye kela chupchap ped par ugta hai,\nKhamoshi se mehnat karne wala hi asmaan chhoota hai! 🍌🌌",
    "Kela khate hi jaise thakan sari mit jati hai,\nSacchi preet se hi toh dil ko rahat mil jati hai! 🍌❤️",
    "Chhilke ko kachre mein daal, aur kele ka tu le swaad,\nBuri baaton ko bhool kar, rakh acchi yaadein yaad! 🍌🚮",
    "Kela jaise har fal mein apna rang jamata hai,\nVyavahaar kushal insaan sabka pyara ban jata hai! 🍌🎨",
    "Jab tak kela poora na chhile, swaad aadhura rehta hai,\nJab tak dil saaf na ho, pyar poora kahan hota hai! 🍌💯",
    "Kela sikhata hai ki mithaas khud ke andar hoti hai,\nBahar dikhawe mein duniya apni keemat khoti hai! 🍌💎",
    "Kele ki sasti keemat uski shreshthta nahi batati,\nInsaan ki saadgi hi uski mahanata hai dikhati! 🍌🌟",
    "Bina kate, bina jale, kela turant khaa sakte hain,\nSaral vyavahar se hum har dil ko jeet sakte hain! 🍌🎈",
    "Kela jitna purana hota, utna hi mithaas lata hai,\nSaccha anubhav insaan ko aur samajhdar banata hai! 🍌🧠",
    "Ped se toot kar bhi kela apni taazgi banaye rakhta hai,\nApno se door hokar bhi sacha dost rishta nibhaye rakhta hai! 🍌🏡",
    "Kele ki shakal ek khubsurat muskaan jaisi hoti hai,\nMuskurahat hi toh har gam ko mitane ki kadi hoti hai! 🍌😊",
    "Kela apna sab kuch bina kisi swarth ke de jata hai,\nNiswarth bhav se jeene wala hi bhagwan ko pata hai! 🍌🙌",
    "A-kela hokar bhi kela kabhi khud ko akela nahi manta,\nKhud par ho yakin toh insaan kisi ko bada nahi manta! 🍌🦅",
    "Jaise kela deta hai urja har nayi subah ke aane par,\nWaise hi umeed rakho har naye sapne ke sajane par! 🍌🌅",
    "Chimpu ki ye seekh hamesha dil mein basakar rakhna,\nKele jaisa ban kar duniya mein apni pehchan zinda rakhna! 🍌🐒"
        "Zindagi us kele ki tarah hai, jise agar waqt par na khaya jaye, toh woh bilkul kaala aur kharab ho jata hai. Waqt par kela khao, khush raho! 🍌✨",
    "Pyar karna toh kela khane jaisa hai, aage badhna hai toh chhilke (ego) ko utarna hi padega! 😉🍌",
    "Duniya gol nahi hai, duniya kele ke aakar ki hai. Isliye yahan sab thode tedhe hain! 🐒🍌",
    "Sacha dost wahi hai jo apna aakhri kela tumhare sath share kare. 🍌🤝",
    "Har subah ek naya kela hai, use tod kar hi meethas ka swad chakhna hai. 🌅🍌",
    "Kele mein bhi sabak hai: bina chhilke utare, koi bhi apna swad nahi dikhata. 💪🍌",
    "Jeet unki hoti hai jo kele ko bhookh se nahi, samajh se khate hain. 🧠🍌",
    "Sapne wahi poore hote hain jo kele ki tarah dhairya se pakte hain. 🌟🍌",
    "Kela khane se pehle uski chhil utarna seekho, zindagi mein bhi mushkilon ko aise hi pehchano. 🔥🍌",
    "Kacha kela bhi kabhi pak jaata hai, bas waqt ka sahara hona chahiye. ⏳🍌",
    "Jab tak kele mein daag nahi, tab tak woh sachcha meetha nahi. Zindagi bhi daagon se nikhar jaati hai. 🌼🍌",
    "Kele ki tarah jhuk kar chalna seekho, toofan bhi nahi gira sakta. 🌊🍌",
    "Jo apna kela dusron ko khilata hai, uski jholi kabhi khali nahi hoti. 🙏🍌",
    "Kele ka rang dekho: peela ruhaniyat hai, hara umang, kala anubhav. 🎨🍌",
    "Kele ki tond tedhi hoti hai, par andar ka meethas seedha dil jeet leta hai. ❤️🍌",
    "Chhilka fek kar aage badho, zindagi ka asli swad andar chhupa hai. 🚶🍌",
    "Jis din kele ki kadar karna seekhoge, us din amiri tumhare paas aayegi. 💎🍌",
    "Kele mein chhupa raaz: kamjor dikhkar bhi sakht se sakht haalat ko meetha kar dena. 🛡️🍌",
    "Thoda sa kela, thoda sa pyaar – din ban jaaye bahaar. 🌸🍌",
    "Kele ki tarah apni pehchan banao, log tumhara naam na bhoolenge. 🏆🍌",
    "Jab zindagi kela de, to usse kehna – main tujhe aur meetha kar dunga. ✨🍌",
    "Kele ki kasam, jo mehnat karta hai wohi meethas paata hai. 🛠️🍌",
    "Kele ko dekhkar mat haso, isi tedhepan mein seedhi baat hoti hai. 😊🍌",
    "Har kela ek kahani hai, kuch meethe, kuch kachche – par sabhi ke apne rang hain. 📖🍌",
    "Akele mat khao kela, baantne se meethas badhta hai. 🤲🍌",
    "Kele ka chhilka pheekha par andar ka swad anmol. Insaan bhi aisa hi hota hai. 🌟🍌",
    "Jo kele ko aadha todta hai, woh poora sukh nahi samajhta. ☯️🍌",
    "Kele pe likha hai: dhairya rakho, pakne do, apne aap meethas aayega. 🕊️🍌",
    "Kele ki chhilkiyon se naa ghabrao, yeh giraane ke liye nahi, utarne ke liye hoti hain. 🧗🍌",
    "Zindagi ke kade sapno ko kele ki tarah meetha kar do, har mushkil halwa ban jayegi. 🍯🍌",
    "Kele mein utni hi shakti hai jitni ek muskaan mein. Dono hi mithaas baant te hain. 😁🍌",
    "Jisne kela khaya, usne jeena seekha. Jisne baanta, usne jeetna seekha. 🥇🍌",
    "Kele ka haath kabhi akela nahi hota, jhund mein khilta hai. Vahi zindagi ki seedh. 🌿🍌",
    "Kele ki umar kam, par yaad baqi rakh jaata hai. Aisa bano tum bhi. 🕰️🍌",
    "Tedha kela tedha raasta, par manzil meethi hoti hai. 🛤️🍌",
    "Kele ki mithaas chhilkewalon ko nahi, khane walon ko pata chalti hai. 🤫🍌",
    "Kele ki tarah apni jaroorat se zyada mat jhuko, toot jaoge. ⚖️🍌",
    "Kele ka rang utarne se nahi, pakne se aata hai. Insaan bhi waqt se nikhrta hai. 🌈🍌",
    "Sapne wahi sach hote hain jo kele ki tarah haath se tod kar khaye jaate hain. 👐🍌",
    "Jo kela khilane aaye, use kabhi bhukha mat jaane do. 🍽️🍌",
    "Kele ki tarah garam dhoop mein bhi apni mithaas mat khona. ☀️🍌",
    "Kele se seekho: bina shor ke apni meethas failana. 🎶🍌",
    "Kele ki tarah agar koi tumhe chhilke phek de, to samajhna ab asli meethas tumhara hai. 🔥🍌",
    "Jab tak kele mein daane nahi, tab tak woh kacha hai. Insaan bhi sangharsh se damdaar hota hai. 💪🍌",
    "Kele ki jhadi ko paani chahiye, sapno ko mehnat. 🌧️🍌",
    "Kele ko mat dekho ke woh tedha hai, dekho ke woh kitna meetha hai. 😌🍌",
    "Kele ki tarah girna bhi seekho, phir uthkar aur meetha banana. 🚀🍌",
    "Jo kele ko pooja ke prasad chadhaye, uski jholi kabhi khali nahi rehti. 🛕🍌",
    "Kele ki tarah saaf raho, andar se meetha, bahar se chamakta. ✨🍌",
    "Kele ke bina prasad adhoora, kele ke bina zindagi sooni. 🙌🍌",
    "Kele ka chhilka utarna seekho toh har mushkil hal ho jati hai. 🔑🍌",
    "Kele ki tarah apni pehchan banao, ki log tumhe dekhkar muskuraye. 😊🍌",
    "Kele ko koi nahi puchta ki tune kitna meethas chhupaya, woh apne aap meetha lagta hai. 🌟🍌",
    "Kele ki tarah kabhi mat ruko, pakte raho, meetha hote raho. 🌱🍌",
    "Kele ki kasam, jo waqt par pak gaya, wohi ameer bana. ⏰🍌",
    "Kele mein bhi gyan hai: andar se mazboot, bahar se komal. 🧘🍌",
    "Kele ki tarah mushkilon ko chhilkar andar ki takat dikhao. 💥🍌",
    "Kele ki mithaas ka raaz: dhoop aur paani dono saha, phir meetha hua. 🌦️🍌",
    "Kele ki tarah jhuk kar baat karo, par kabhi apni mithaas mat girne do. 🎯🍌",
    "Kele se seekho, thode se mein bhi bada sukh dena. 🎁🍌",
    "Kele ki tarah raaste mein bhi agar koi tod le, to bhi meethas baant do. 🛣️🍌",
    "Kele ki chhilkiyon ko naa gin, andar ka meethas chakh. 🧭🍌",
    "Kele ke liye naa koi jaat, naa koi baat; woh sabko meetha lagta hai. 🌍🍌",
    "Kele ki tarah apne sapno ko dhairya se pakne do, waqt aane par khud meethas milega. 🌄🍌",
    "Kele ki tarah agar koi tumhe chhilke utaare, toh samajhna woh tumhari mithaas dekhna chahta hai. 👀🍌",
    "Kele ki mithaas uske andar hoti hai, waise hi insaan ki khoobi uske andar. 🧠🍌",
    "Kele ki tarah apni mithaas ko kabhi chhupao mat, duniya ko meetha karo. 🌎🍌",
    "Kele ki tarah agar koi tumhe utha kar rakhe, toh khud ko uske kabil banao. 🏺🍌",
    "Kele ki tarah kabhi akela mat raho, jhund mein mithaas badhti hai. 👥🍌",
    "Kele ki tarah meethas baantne se khud kam nahi hota, badhta hai. 📈🍌",
    "Kele ki tarah tedha hona bhi ek kala hai, seedha dil rakho toh sab theek ho jata hai. 💖🍌",
    "Kele ki tarah waqt se pehle mat todo, apne aap pakne do. 🍃🍌",
    "Kele ki tarah agar koi tumhe kaala kahe, toh kehna ki main pakkar meetha ho gaya. 🖤🍌",
    "Kele ki tarah kabhi apni mithaas ko bhoolna mat, wahi tumhari pehchan hai. 🏅🍌",
    "Kele ki tarah duniya ko bata do ki meethas chhilkewalon ke liye nahi, khane walon ke liye hai. 🍬🍌",
    "Kele ki tarah gir kar bhi uttho, aur phir se meetha bano. 🌀🍌",
    "Kele ki tarah apni khushi khud bano, kisi ke haath ki chhilki mat bano. 🦋🍌",
    "Kele ki tarah kabhi apne rang pe naa itrao, meethas to andar ka hai. 🌈🍌",
    "Kele ki tarah hamesha swaadisht raho, chaahe koi kahe tedhe ho. 😜🍌",
    "Kele ki tarah apni umar bhar meethas do, jaate jaate bhi kisi ke kaam aao. 🕯️🍌",
    "Kele ki tarah mushkilon ko chhilkar andar ki meethas ko bahar lao. 🗝️🍌",
    "Kele ki tarah kuch log tedhe hote hain par unka dil meetha hota hai. 💗🍌",
    "Kele ki tarah sabko apni mithaas ka ehsaas karwao, par khud pe naa garv karo. 🙇🍌",
    "Kele ki tarah kabhi haarna mat, hamesha pakte raho. 🔄🍌",
    "Kele ki tarah agar koi tumhe tod de, toh use mithaas se bhar do. 🌼🍌",
    "Kele ki tarah bina shikayat ke apna kaam karo, duniya apne aap meethi ho jayegi. 🌻🍌",
    "Kele ki tarah har mausam mein apna swad banae rakhna. 🌸🍌",
    "Kele ki tarah kachhepan mein bhi ummeed rakho, ek din pakna hi hai. 🌱🍌",
    "Kele ki tarah apni mithaas ko kabhi naa becho, baant do. 🎁🍌",
    "Kele ki tarah thoda sa tedha hona bhi zaroori hai, seedha insaan to patthar hota hai. 🗿🍌",
    "Kele ki tarah duniya ki najron se chhup kar bhi meetha raho. 🌙🍌",
    "Kele ki tarah apne andar ki mithaas ko pehchano, fir koi tumhe nahi rok sakta. 🚀🍌",
    "Kele ki tarah bina kisi bhasha ke sabko samajh aana. 🗣️🍌",
    "Kele ki tarah apni jad se juda raho, tabhi meethas aayega. 🌳🍌",
    "Kele ki tarah waqt aane par khud hi toot kar baant do, yahi zindagi hai. 🌊🍌",
    "Kele ki tarah kabhi apni mithaas par sandeh mat karo, woh tumhari takat hai. 💎🍌",
    "Kele ki tarah meethas ka raaz sirf unhe pata hai jo andar utar kar dekhte hain. 🔍🍌",
    "Kele ki tarah zindagi ko meetha banana hai, toh thoda sa pyaar aur thoda sa dhairya chahiye. 💖⏳🍌",
    "Kele ki tarah apni mithaas ko kabhi kam mat samjho, ek kela bhi bhookh mita sakta hai. 🍌❤️",
]

